#!/bin/sh
# Gate: a `.deps` sidecar does not outlive its truth (v6.5.37, A7).
#
# TWO HALVES OF ONE HAZARD — a sidecar that has stopped describing its bundle.
#
#   1. `cyrius distlib` never REMOVED one. The `vec_len(req_leaves) > 0` guard is deliberate
#      (v6.5.29: a package with genuinely no leaves should not gain a stray file) but it only
#      decides whether to WRITE. So a package that dropped its whole `[deps] stdlib` went on
#      publishing the old list. Measured at 6.5.36: 7 stale leaves survived the leaf set
#      going empty, and `cyrius deps` in a consumer kept vendoring all seven.
#
#   2. `cyrius distlib --check` could not SEE that. The comparison was wrapped in
#      `if (file_exists(regenerated) == 1)`, so when the fresh run produced no sidecar —
#      exactly what happens once the leaf set empties — the check was skipped and reported
#      *current* over a committed file that no longer described anything. The ABSENCE of the
#      regenerated file is the signal, not a reason to skip.
#
# ⭐ WHY OVER-REPORTING IS THE DIRECTION THAT MATTERS: an under-reported sidecar fails
# silently at the consumer's compile step, but an over-reported one names leaves the consumer
# must resolve, and a name that is not in the stdlib is a HARD resolver error before
# compilation is reached (the dhancha `kashi_font_data` shape — crab and puka could not
# resolve it at all). A sidecar that has become false must go, not linger.
#
# ⚠ REMOVAL, NOT AN EMPTY FILE. That keeps v6.5.29's intent intact — no stray files for
# packages that never had leaves, and no lie for packages that stopped having them. Axis 3
# pins the "never had any" case so a future change cannot start emitting empty base sidecars
# for every dependency-free package.
set -eu

ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
CYRIUS=${CYRIUS_BIN:-"$ROOT/build/cyrius"}
[ -x "$CYRIUS" ] || CYRIUS=$(command -v cyrius)
VER=$(cat "$ROOT/VERSION")
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
fail() { echo "FAIL: distlib_sidecar_staleness: $1"; exit 1; }
# CYRIUS_RESOLVED=1: a fixture pinning another version would re-exec an older binary.
run() { ( cd "$1" && shift; CYRIUS_RESOLVED=1 "$CYRIUS" "$@" 2>&1 ); }

mkproj() {  # mkproj <dir> <declared-stdlib-or-empty> <body>
    d="$WORK/$1"; mkdir -p "$d/src"
    printf '%s\n' "$3" > "$d/src/lib.cyr"
    {
        printf '[package]\nname = "stprobe"\nversion = "0.1.0"\ncyrius = "%s"\n' "$VER"
        printf '[lib]\nmodules = ["src/lib.cyr"]\n'
        [ -n "$2" ] && printf '[deps]\nstdlib = [%s]\n' "$2"
    } > "$d/cyrius.cyml"
    echo "$d"
}

# ── axis 1: a sidecar whose leaf set has emptied is REMOVED ────────────────────────
A=$(mkproj a '"alloc", "str", "string", "syscalls", "io", "fmt", "vec"' \
    'fn st_fn(): i64 { var s = str_from("x"); return 1; }')
run "$A" distlib >/dev/null 2>&1 || true
[ -f "$A/dist/stprobe.deps" ] || fail "axis 1 premise: no sidecar produced for a package WITH leaves"
BEFORE=$(grep -c '^[a-z]' "$A/dist/stprobe.deps" || true)
[ "$BEFORE" -ge 5 ] || fail "axis 1 premise: expected >= 5 leaves, got $BEFORE"
# Drop the dependencies entirely, and the code that needed them.
printf '[package]\nname = "stprobe"\nversion = "0.1.0"\ncyrius = "%s"\n[lib]\nmodules = ["src/lib.cyr"]\n' "$VER" > "$A/cyrius.cyml"
echo 'fn st_fn(): i64 { return 1; }' > "$A/src/lib.cyr"
run "$A" distlib >/dev/null 2>&1 || true
[ -f "$A/dist/stprobe.deps" ] && fail "axis 1: the sidecar survived with $(grep -c '^[a-z]' "$A/dist/stprobe.deps") stale leaves after the package dropped every dependency"

# ── axis 2: --check treats "committed present, regenerated absent" as DRIFT ─────────
# The only axis that fails against the `if (file_exists(regenerated))` wrapper.
printf '# cyrius dep sidecar - stdlib leaves this fold requires in scope.\n# Auto-generated by `cyrius distlib`; consumed by `cyrius deps`.\nalloc\nstr\nstring\n' > "$A/dist/stprobe.deps"
set +e
OUT=$(cd "$A" && CYRIUS_RESOLVED=1 "$CYRIUS" distlib --check 2>&1); RC=$?
set -e
[ "$RC" -ne 0 ] || fail "axis 2: --check reported success over a committed sidecar the package no longer generates"
echo "$OUT" | grep -q "STALE" || fail "axis 2: --check exited non-zero but did not say STALE: $(echo "$OUT" | tail -2)"

# ── axis 3: a package that NEVER had leaves gains no stray sidecar ──────────────────
# Pins v6.5.29's intent. Without this, "always write an empty sidecar" would pass axes 1-2
# while adding a file to every dependency-free package in the ecosystem.
B=$(mkproj b '' 'fn st_none(): i64 { return 1; }')
run "$B" distlib >/dev/null 2>&1 || true
[ -f "$B/dist/stprobe.cyr" ] || fail "axis 3 premise: no bundle produced"
[ -f "$B/dist/stprobe.deps" ] && fail "axis 3: a package with no declared leaves gained a stray sidecar"

# ── axis 4: ANTI-VACUOUS — a package WITH leaves still gets one, and --check passes ─
# Without this, never writing a sidecar at all passes axes 1-3.
C=$(mkproj c '"alloc", "io"' 'fn st_ok(): i64 { return 1; }')
run "$C" distlib >/dev/null 2>&1 || true
[ -f "$C/dist/stprobe.deps" ] || fail "axis 4: a package WITH declared leaves produced no sidecar"
grep -qx 'alloc' "$C/dist/stprobe.deps" || fail "axis 4: the sidecar lost its declared leaves"
set +e
(cd "$C" && CYRIUS_RESOLVED=1 "$CYRIUS" distlib --check >/dev/null 2>&1); RC4=$?
set -e
[ "$RC4" -eq 0 ] || fail "axis 4: --check reported drift on a freshly generated, unmodified bundle (exit $RC4)"

echo "PASS: distlib_sidecar_staleness (emptied sidecar removed, absent-vs-committed is drift, no stray file, fresh bundle still clean)"
