#!/bin/sh
# check: serial — axis 6 times two builds against each other (2x limit, ~1.77 on a quiet box); in the 8-wide pool beside the cross-OS legs it read 2350 vs 919 ms at the 6.7.1 gate, so the parallel check.sh runs it alone, after its pool (6.7.1)
# embed_build.sh — 6.6.19 (P2, E2). `[embed] NAME = "path"` reaches source: every compile carries
# the file's bytes as `NAME()` / `NAME_len()`, generated by cbt into the materialized unit BEFORE
# `#@srcline` (cbt/build.cyr `_embed_render`). The probe programs write `NAME()` for `NAME_len()`
# bytes and the gate `cmp`s that against the file — the bytes are never read back through cbt.
#
# AXES (on the pre-6.6.19 CLI `NAME` is undefined, so every axis is RED)
#   1. text: `"`, `\`, CR/LF, tabs; lines starting `#ifdef`, `#@srcline`, `#@file`, `include "x"`;
#      a word equal to a `[build] defines` name; UTF-8 — all round-trip byte-exact (the escaping
#      keeps each literal one pure-ASCII line, so no preprocessor rule can see the data).
#   2. a 256-value binary (NULs included) round-trips; an empty file has NAME_len() == 0.
#   3. the prelude is line-neutral: an error on the entry's line 3 reports `<source>:3`.
#   4. freshness: edit the data file, rebuild, the new bytes come out (no generator step).
#   5. `cyrius test` of a .tcyr sees the embed.
#   6. a 2,000,000-byte random embed + stdlib + 3,000 other literals builds and round-trips, in
#      under 2x the time of the SAME bytes as a hand-written module included LAST (the consumer
#      generators' placement). The prelude puts the embed FIRST, where cycc's linear interning
#      scan made every later literal re-scan 2 MB (measured 12.4 s vs 0.87 s before B0b) — so this
#      also guards B0b's interning index at the CLI level.
#   7. near the pool: a 2,097,150-byte embed (the per-file cap) COMPILES and its length is right,
#      in a fixture with no [package] version and no other literal (#@pkgver would add one).
#   8. collisions are REFUSED by cbt, by name: a NAME equal to a stdlib fn (alloc_reset, and alloc of
#      another arity), a NAME whose NAME_len is one (`vec` -> vec_len), a fn in src/ and a var in a
#      [build] module. ("Last definition wins" was the earlier rule: in the build the stdlib's
#      definition silently won over the embed; in a CONSUMER of a bundle the embed silently replaced
#      the stdlib fn.) A SEPARATE included file calling NAME() gets the bytes (the prelude shares
#      <source>'s file id, and visibility is keyed on file id since 6.5.38).
#   9. (6.6.20, CBTB-04) the collision check sees what `[deps]` VENDORS: a path dep whose module
#      declares NAME — or only NAME_len — is refused on a FRESH checkout's first build (no lib/;
#      the check ran before cmd_deps, so the build exited 0 with the dep's NAME() winning and only
#      the next build refused), and after a dep change that ADDS NAME to an already-vendored lib/.
#      Anti-over-reach: a stale lib/ module declaring NAME, from a dep version that has since
#      dropped it, does not refuse — the check reads lib/ as the resolve leaves it.
#  10. (6.7.6, A1) the project's OWN fold is not an owner: the pinned stdlib snapshot's leaf named
#      for the project's [package] name carries the module generated from this very [embed]
#      (sankoch 2.8.3 building itself on the cyrius that re-vendored it was refused by its own
#      lib/sankoch.cyr). Every other owner still refuses: another fold's NAME for that project, the
#      fold's NAME for a project of another name or of none, and src/ for the folded project.
#
# MUTATION LEDGER (axis 10, measured 6.7.6; each mutant built in a SCRATCH copy of the tree —
# cbt/, lib/, src/version_str.cyr, build/cycc, VERSION and this gate — and the gate run there;
# the unmutated copy PASSES, each mutant turns the rows named RED):
#   M1  commands.cyr _embed_collisions: the own-leaf skip removed (the 6.7.5 code)   10 own, src/
#   M2  the skip taken for EVERY leaf                                10 other-leaf, other-name, no-name
#   M3  the skip taken when the project has no [package] name (own == 0)               10 no-name
#   M4  the own leaf ENDS the check (`return n` for `continue`)   10 src/ (and other-leaf when the
#       snapshot's directory order lists foldpkg first)
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT" || exit 2
CC=${CYCC:-"$ROOT/build/cycc"}
[ -x "$CC" ] || { echo "SKIP: embed_build: no compiler at $CC"; exit 77; }
W=$(mktemp -d) && [ -d "$W" ] || { echo "FAIL: embed_build: mktemp -d failed (TMPDIR=${TMPDIR:-/tmp})"; exit 1; }
trap 'rm -rf "$W"' EXIT
FAIL=0
fail() { echo "  FAIL: $*"; FAIL=$((FAIL + 1)); }
"$CC" < cbt/cyrius.cyr > "$W/cyrius" 2> "$W/build.err" || { echo "FAIL: embed_build: cbt/cyrius.cyr does not build"; tail -3 "$W/build.err"; exit 1; }
chmod +x "$W/cyrius"
mkdir -p "$W/home/bin"; cp "$CC" "$W/home/bin/cycc"
P="$W/p"
mkdir -p "$P/data" "$P/src" "$P/tests"
cp -R "$ROOT/lib" "$P/lib"
cli() { ( cd "$P" && env -u CYRIUS_DCE -u CYRIUS_DEFINES CYRIUS_HOME="$W/home" CYRIUS_RESOLVED=1 "$W/cyrius" "$@" ); }
# mf <entry> <[embed] lines...> — a manifest with no [package] version
mf() { e=$1; shift; { printf '[build]\nentry = "%s"\noutput = "build/main"\ndefines = ["FOO"]\n[embed]\n' "$e"; for l in "$@"; do printf '%s\n' "$l"; done; } > "$P/cyrius.cyml"; }
# build, then run build/main with stdout to $W/got; rc of the run in $run
br() { rm -rf "$P/build" "$W/got"; brc=0; cli build > "$W/b.out" 2>&1 || brc=$?; run=x; [ "$brc" = 0 ] && { run=0; "$P/build/main" > "$W/got" || run=$?; }; }

# ── axis 1 / 2: text, binary, empty ──────────────────────────────────────────────────────
x=$FAIL
printf 'a "quoted" \\ back\\slash\r\n\ttabbed\n#ifdef FOO\n#@srcline\n#@file evil.cyr\ninclude "x"\nFOO is defined\nh\303\251llo w\303\266rld \342\202\254\n' > "$P/data/t.txt"
i=0; while [ $i -lt 256 ]; do printf "\\$(printf '%03o' $i)"; i=$((i + 1)); done > "$P/data/b.bin"
: > "$P/data/e.bin"
[ "$(wc -c < "$P/data/b.bin" | tr -d ' ')" = 256 ] || fail "axis 2: the 256-value fixture is $(wc -c < "$P/data/b.bin") bytes"
printf 'syscall(1, 1, T(), T_len());\nsyscall(1, 1, B(), B_len());\nsyscall(60, E_len());\n' > "$P/main.cyr"
mf main.cyr 'T = "data/t.txt"' 'B = "data/b.bin"' 'E = "data/e.bin"'
br
cat "$P/data/t.txt" "$P/data/b.bin" > "$W/want"
if [ "$brc" != 0 ]; then fail "axes 1-2: the build failed (exit $brc): $(grep -E 'error|warning: undefined' "$W/b.out" | head -2 | tr '\n' ' ')"
else
    cmp -s "$W/want" "$W/got" || fail "axes 1-2: the bytes did not round-trip ($(wc -c < "$W/got" | tr -d ' ') of $(wc -c < "$W/want" | tr -d ' '))"
    [ "$run" = 0 ] || fail "axis 2: the empty embed's E_len() is $run, not 0"
fi
[ "$FAIL" = "$x" ] && echo "  ok axes 1-2: quotes, backslashes, CR/LF, tabs, directive-shaped lines, a define name, UTF-8, all 256 byte values and an empty file round-trip"

# ── axis 3: line-neutral ─────────────────────────────────────────────────────────────────
x=$FAIL
printf 'var a = 1;\nvar b = 2;\nvar c = ;\n' > "$P/main.cyr"
br
[ "$brc" != 0 ] && grep -q '<source>:3:' "$W/b.out" || fail "axis 3: an error on the entry's line 3 is not reported at <source>:3: $(grep error "$W/b.out" | head -1)"
[ "$FAIL" = "$x" ] && echo "  ok axis 3: the prelude is line-neutral (<source>:3)"

# ── axis 4: freshness ────────────────────────────────────────────────────────────────────
x=$FAIL
printf 'syscall(1, 1, T(), T_len());\nsyscall(60, 0);\n' > "$P/main.cyr"
mf main.cyr 'T = "data/f.txt"'
printf 'first\n' > "$P/data/f.txt"; br
cmp -s "$P/data/f.txt" "$W/got" || fail "axis 4: the first build did not carry the file"
printf 'second, longer\n' > "$P/data/f.txt"; br
cmp -s "$P/data/f.txt" "$W/got" || fail "axis 4: after editing the data file the rebuild still carries old bytes: $(cat "$W/got" 2>/dev/null)"
[ "$FAIL" = "$x" ] && echo "  ok axis 4: an edited data file is in the next build, with no generator step"

# ── axis 5: cyrius test ──────────────────────────────────────────────────────────────────
x=$FAIL
printf 'abc' > "$P/data/s.txt"
mf main.cyr 'S = "data/s.txt"'
printf 'if (S_len() == 3) { if (load8(S() + 2) == 99) { syscall(60, 0); } }\nsyscall(60, 1);\n' > "$P/tests/embed.tcyr"
rc=0; cli test tests/embed.tcyr > "$W/t.out" 2>&1 || rc=$?
[ "$rc" = 0 ] || fail "axis 5: cyrius test of a .tcyr reading the embed exited $rc: $(grep -E 'error|FAIL' "$W/t.out" | head -2 | tr '\n' ' ')"
[ "$FAIL" = "$x" ] && echo "  ok axis 5: cyrius test compiles the embed into a .tcyr"

# ── axis 6: 2 MB + stdlib + 3,000 literals, and its cost ─────────────────────────────────
x=$FAIL
head -c 2000000 /dev/urandom > "$P/data/big.bin"
{ for m in string fmt alloc io vec str args fs process syscalls; do printf 'include "lib/%s.cyr"\n' "$m"; done
  printf 'alloc_init();\nsyscall(1, 1, BIG(), BIG_len());\n'
  i=0; while [ $i -lt 3000 ]; do printf 'var s%d = "small literal %d";\n' $i $i; i=$((i + 1)); done; } > "$W/body"
{ cat "$W/body"; printf 'syscall(60, 0);\n'; } > "$P/big.cyr"
# the baseline: the same bytes as a hand-written module included LAST (generated here, with od —
# the same escaping, so the two compiles lex the same literal)
{ printf 'fn BIG(): i64 {\n    return "'
  od -An -v -tu1 "$P/data/big.bin" | tr -s ' \n' '\n\n' | awk 'NF { c = $1 + 0
      if (c == 34) printf "\\\""; else if (c == 92) printf "\\\\"; else if (c >= 32 && c <= 126) printf "%c", c; else printf "\\x%02x", c }'
  printf '";\n}\nfn BIG_len(): i64 { return 2000000; }\n'; } > "$P/big_mod.cyr"
{ cat "$W/body"; printf 'include "big_mod.cyr"\nsyscall(60, 0);\n'; } > "$P/base.cyr"
printf '[build]\nentry = "base.cyr"\noutput = "build/main"\n' > "$P/cyrius.cyml"
t0=$(date +%s%N); br; t1=$(date +%s%N)
base_ms=$(( (t1 - t0) / 1000000 ))
cmp -s "$P/data/big.bin" "$W/got" || fail "axis 6: the hand-written baseline does not round-trip (exit $brc) — the comparison would be meaningless"
mf big.cyr 'BIG = "data/big.bin"'
t0=$(date +%s%N); br; t1=$(date +%s%N)
emb_ms=$(( (t1 - t0) / 1000000 ))
cmp -s "$P/data/big.bin" "$W/got" || fail "axis 6: the 2,000,000-byte embed does not round-trip (exit $brc): $(grep -E 'error' "$W/b.out" | head -1)"
[ "$emb_ms" -lt $((2 * base_ms + 200)) ] || fail "axis 6: [embed] build took ${emb_ms} ms, the same bytes included last ${base_ms} ms — over 2x: the embed sits FIRST in the pool, so cycc's literal interning is paying for it (B0b)"
[ "$FAIL" = "$x" ] && echo "  ok axis 6: 2,000,000 B + stdlib + 3,000 literals round-trips; ${emb_ms} ms vs ${base_ms} ms hand-written-last"

# ── axis 7: the per-file cap compiles ────────────────────────────────────────────────────
x=$FAIL
head -c 2097150 /dev/zero | tr '\0' 'a' > "$P/data/cap.txt"
printf 'if (CAP_len() == 2097150) { if (load8(CAP() + 2097149) == 97) { if (load8(CAP() + 2097150) == 0) { syscall(60, 0); } } }\nsyscall(60, 1);\n' > "$P/cap.cyr"
printf '[build]\nentry = "cap.cyr"\noutput = "build/main"\n[embed]\nCAP = "data/cap.txt"\n' > "$P/cyrius.cyml"
br
[ "$brc" = 0 ] && [ "$run" = 0 ] || fail "axis 7: a 2,097,150-byte embed (cbt's per-file cap) does not compile and check out (build $brc, run $run): $(grep -E 'error' "$W/b.out" | head -1) — cbt's cap and cycc's pool disagree"
[ "$FAIL" = "$x" ] && echo "  ok axis 7: a 2,097,150-byte embed — the per-file cap — compiles, length and NUL right"

# ── axis 8: collisions are REFUSED, never "last definition wins" ─────────────────────────
x=$FAIL
# owned <label> <[embed] line> <expected text>: the build exits non-zero, names it, builds nothing
owned() {
    mf main.cyr "$2"; br
    [ "$brc" != 0 ] || fail "axis 8 $1: an [embed] colliding with an existing definition built (run $run)"
    grep -qF "$3" "$W/b.out" || fail "axis 8 $1: no '$3' refusal: $(grep -E 'error|warn' "$W/b.out" | head -1)"
}
printf 'include "lib/alloc.cyr"\nalloc_init();\nsyscall(60, 0);\n' > "$P/main.cyr"
owned "stdlib fn"     'alloc_reset = "data/s.txt"' 'error: cyrius.cyml [embed] alloc_reset: alloc_reset is already declared by lib/'
owned "stdlib arity"  'alloc = "data/s.txt"'       'error: cyrius.cyml [embed] alloc: alloc is already declared by lib/'
owned "NAME_len"      'vec = "data/s.txt"'         'error: cyrius.cyml [embed] vec: vec_len is already declared by lib/vec.cyr'
printf 'fn PROJ_FN(): i64 { return 1; }\n' > "$P/src/proj.cyr"
owned "src/ fn"       'PROJ_FN = "data/s.txt"'     'error: cyrius.cyml [embed] PROJ_FN: PROJ_FN is already declared by src/proj.cyr'
rm -f "$P/src/proj.cyr"
mkdir -p "$P/mods"; printf 'var MOD_V = 3;\n' > "$P/mods/m.cyr"
{ printf '[build]\nentry = "main.cyr"\noutput = "build/main"\nmodules = ["mods/m.cyr"]\n[embed]\nMOD_V = "data/s.txt"\n'; } > "$P/cyrius.cyml"; br
[ "$brc" != 0 ] && grep -qF 'error: cyrius.cyml [embed] MOD_V: MOD_V is already declared by mods/m.cyr' "$W/b.out" \
    || fail "axis 8 [build] modules: a NAME a [build] module declares was not refused (exit $brc): $(grep error "$W/b.out" | head -1)"
printf 'fn other(): i64 { return load8(GREET() + 2); }\n' > "$P/src/other.cyr"
printf 'include "src/other.cyr"\nsyscall(60, other());\n' > "$P/main.cyr"
mf main.cyr 'GREET = "data/s.txt"'
br
[ "$brc" = 0 ] && [ "$run" = 99 ] || fail "axis 8 other file: an included file calling GREET() did not get the bytes (build $brc, run $run, want 99)"
[ "$FAIL" = "$x" ] && echo "  ok axis 8: a NAME / NAME_len the stdlib, src/ or a [build] module declares is refused by name; another file calls NAME()"

# ── axis 9: a dep module vendored by THIS build is an owner too ──────────────────────────
x=$FAIL
Q="$W/q"; D="$W/dep"
mkdir -p "$Q/data" "$D/dist"
printf 'hello-embed\n' > "$Q/data/h.txt"
printf 'syscall(1, 1, BLOB(), BLOB_len());\nsyscall(60, 0);\n' > "$Q/main.cyr"
printf '[build]\nentry = "main.cyr"\noutput = "build/main"\n[embed]\nBLOB = "data/h.txt"\n[deps.foo]\npath = "%s"\nmodules = ["dist/foo.cyr"]\n' "$D" > "$Q/cyrius.cyml"
# qb: build Q, then run build/main into $W/got (rc of the run in $run, x when nothing was built)
qb() { rm -rf "$Q/build" "$W/got"; brc=0; ( cd "$Q" && env -u CYRIUS_DCE -u CYRIUS_DEFINES HOME="$W/home" CYRIUS_HOME="$W/home" CYRIUS_RESOLVED=1 "$W/cyrius" build ) > "$W/b.out" 2>&1 || brc=$?; run=x; [ -x "$Q/build/main" ] && { run=0; "$Q/build/main" > "$W/got" || run=$?; }; }
gotp() { tr -d '\000' < "$W/got" 2>/dev/null | head -c 80; }   # what the probe printed (NAME_len can over-read)
# fresh <label> <dep module text> <expected text>: no lib/ — the FIRST build refuses by name
fresh() {
    rm -rf "$Q/lib" "$Q/cyrius.lock"; printf '%s\n' "$2" > "$D/dist/foo.cyr"; qb
    [ "$brc" != 0 ] || fail "axis 9 $1: the first build of a fresh checkout exited 0 (run $run, printed '$(gotp)') — the collision check ran before the dep was vendored"
    [ "$run" = x ] || fail "axis 9 $1: a refused build left build/main behind"
    grep -qF "$3" "$W/b.out" || fail "axis 9 $1: no '$3' refusal: $(grep -E 'error|warn' "$W/b.out" | head -1)"
}
fresh "fresh NAME"     'fn BLOB(): i64 { return "from-dep"; }' 'error: cyrius.cyml [embed] BLOB: BLOB is already declared by lib/foo.cyr'
fresh "fresh NAME_len" 'fn BLOB_len(): i64 { return 64; }'     'error: cyrius.cyml [embed] BLOB: BLOB_len is already declared by lib/foo.cyr'
# a vendored lib/ without the name builds; the dep then ADDS it, and the next build refuses
rm -rf "$Q/lib" "$Q/cyrius.lock"; printf 'fn foo_other(): i64 { return 1; }\n' > "$D/dist/foo.cyr"; qb
[ "$brc" = 0 ] && [ "$run" = 0 ] && cmp -s "$Q/data/h.txt" "$W/got" || fail "axis 9 dep bump: the build before the bump did not build and carry the embed (build $brc, run $run): $(grep -E 'error' "$W/b.out" | head -1)"
printf 'fn foo_other(): i64 { return 1; }\nfn BLOB(): i64 { return "from-dep-v2"; }\n' > "$D/dist/foo.cyr"; qb
[ "$brc" != 0 ] && grep -qF 'error: cyrius.cyml [embed] BLOB: BLOB is already declared by lib/foo.cyr' "$W/b.out" \
    || fail "axis 9 dep bump: a dep change that adds BLOB was not refused on the build that vendored it (build $brc, run $run, printed '$(gotp)')"
# anti-over-reach: lib/foo.cyr still declares BLOB, the dep has dropped it -> the resolve rewrites it
printf 'fn foo_other(): i64 { return 2; }\n' > "$D/dist/foo.cyr"; qb
[ "$brc" = 0 ] && [ "$run" = 0 ] && cmp -s "$Q/data/h.txt" "$W/got" \
    || fail "axis 9 stale lib/: a name a dep has DROPPED was refused from the stale lib/ (build $brc, run $run): $(grep -E 'error' "$W/b.out" | head -1)"
[ "$FAIL" = "$x" ] && echo "  ok axis 9: a NAME / NAME_len a [deps] module declares is refused on the build that vendors it (fresh checkout, dep bump); a name the dep dropped is not"

# ── axis 10: the project's own fold in the pinned stdlib is not an owner ─────────────────
x=$FAIL
V=$(tr -d '[:space:]' < VERSION)
SL="$W/home/versions/$V/lib"; R="$W/r"
mkdir -p "$SL" "$R/data" "$R/src"
# the snapshot: foldpkg's bundle as `cyrius distlib` writes it (the generated module, stale bytes)
printf '# [embed] FOLD_BLOB <- data/x.txt (4 bytes). Generated by cyrius from the file; edit the file.\nfn FOLD_BLOB(): i64 {\n    return "old\\n";\n}\nfn FOLD_BLOB_len(): i64 { return 4; }\nfn foldpkg_api(): i64 { return FOLD_BLOB_len(); }\n' > "$SL/foldpkg.cyr"
printf 'fn OTHER_BLOB(): i64 { return 0; }\n' > "$SL/otherfold.cyr"
printf 'own-bytes\n' > "$R/data/x.txt"
printf 'syscall(1, 1, FOLD_BLOB(), FOLD_BLOB_len());\nsyscall(60, 0);\n' > "$R/main.cyr"
# rmf <[package] header + lines> <[embed] line>: a manifest pinned to $V ([package] cyrius picks
# the snapshot); rb: build R, run it into $W/got
rmf() { { printf '%s' "$1"; printf 'cyrius = "%s"\n[build]\nentry = "main.cyr"\noutput = "build/main"\n[embed]\n%s\n' "$V" "$2"; } > "$R/cyrius.cyml"; }
rb() { rm -rf "$R/build" "$W/got"; brc=0; ( cd "$R" && env -u CYRIUS_DCE -u CYRIUS_DEFINES HOME="$W/home" CYRIUS_HOME="$W/home" CYRIUS_RESOLVED=1 "$W/cyrius" build ) > "$W/b.out" 2>&1 || brc=$?; run=x; [ -x "$R/build/main" ] && { run=0; "$R/build/main" > "$W/got" || run=$?; }; }
# rowned <label> <[package] lines> <[embed] line> <expected text>: refused by name, nothing built
rowned() {
    rmf "$2" "$3"; rb
    [ "$brc" != 0 ] && [ "$run" = x ] || fail "axis 10 $1: an [embed] colliding with an existing definition built (build $brc, run $run)"
    grep -qF "$4" "$W/b.out" || fail "axis 10 $1: no '$4' refusal: $(grep -E 'error|warn' "$W/b.out" | head -1)"
}
PK='[package]
name = "foldpkg"
version = "1.0.0"
'
rmf "$PK" 'FOLD_BLOB = "data/x.txt"'; rb
[ "$brc" = 0 ] && [ "$run" = 0 ] && cmp -s "$R/data/x.txt" "$W/got" \
    || fail "axis 10 own: project foldpkg's [embed] FOLD_BLOB was refused by (or lost to) its own fold, lib/foldpkg.cyr (build $brc, run $run, printed '$(gotp)'): $(grep -E 'error' "$W/b.out" | head -1)"
rowned "other-leaf" "$PK" 'OTHER_BLOB = "data/x.txt"' \
    'error: cyrius.cyml [embed] OTHER_BLOB: OTHER_BLOB is already declared by the stdlib leaf otherfold'
rowned "other-name" '[package]
name = "notfold"
' 'FOLD_BLOB = "data/x.txt"' 'error: cyrius.cyml [embed] FOLD_BLOB: FOLD_BLOB is already declared by the stdlib leaf foldpkg'
rowned "no-name" '[package]
' 'FOLD_BLOB = "data/x.txt"' \
    'error: cyrius.cyml [embed] FOLD_BLOB: FOLD_BLOB is already declared by the stdlib leaf foldpkg'
printf 'fn FOLD_BLOB(): i64 { return 0; }\n' > "$R/src/blob.cyr"
rowned "src/" "$PK" 'FOLD_BLOB = "data/x.txt"' 'error: cyrius.cyml [embed] FOLD_BLOB: FOLD_BLOB is already declared by src/blob.cyr'
rm -f "$R/src/blob.cyr"
[ "$FAIL" = "$x" ] && echo "  ok axis 10: the leaf named for the project's [package] is its own fold, not an owner; another fold, another (or no) [package] name, and src/ still refuse by name"

[ "$FAIL" = 0 ] || { echo "FAIL: embed_build ($FAIL)"; exit 1; }
echo "PASS: embed_build"
