#!/bin/sh
# embed_build.sh — 6.6.19 (P2, E2). `[embed] NAME = "path"` reaches source: every compile carries
# the file's bytes as `NAME()` / `NAME_len()`, generated by cbt into the materialized unit BEFORE
# `#@srcline` (cbt/build.cyr `_embed_render`). The probe programs write `NAME()` for `NAME_len()`
# bytes and the gate `cmp`s that against the file — the bytes are never read back through cbt.
#
# AXES (on the pre-6.6.19 CLI `NAME` is undefined, so every axis is RED)
#   1. text: `"`, `\`, CR/LF, tabs; lines starting `#ifdef`, `#@srcline`, `#@file`, `include "x"`;
#      a word equal to a `[build] defines` name; UTF-8 — all round-trip byte-exact (the escaping
#      keeps each literal one pure-ASCII line, so no preprocessor rule can see the data).
#   2. a 256-value binary (NULs included) round-trips; an empty file has NAME_len() == 0.
#   3. the prelude is line-neutral: an error on the entry's line 3 reports `<source>:3`.
#   4. freshness: edit the data file, rebuild, the new bytes come out (no generator step).
#   5. `cyrius test` of a .tcyr sees the embed.
#   6. a 2,000,000-byte random embed + stdlib + 3,000 other literals builds and round-trips, in
#      under 2x the time of the SAME bytes as a hand-written module included LAST (the consumer
#      generators' placement). The prelude puts the embed FIRST, where cycc's linear interning
#      scan made every later literal re-scan 2 MB (measured 12.4 s vs 0.87 s before B0b) — so this
#      also guards B0b's interning index at the CLI level.
#   7. near the pool: a 2,097,150-byte embed (the per-file cap) COMPILES and its length is right,
#      in a fixture with no [package] version and no other literal (#@pkgver would add one).
#   8. collisions — what the user sees: an embed NAME equal to a 0-arity stdlib fn (alloc_reset)
#      warns `duplicate fn` at the stdlib's line (the LATER definition, in a real file) and builds;
#      one equal to `alloc` (arity 1) is the v6.5.37 arity-mismatch ERROR naming lib/alloc.cyr; a
#      SEPARATE included file calling NAME() gets the bytes (the prelude shares <source>'s file
#      id, and visibility is keyed on file id since 6.5.38).
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT" || exit 2
CC=${CYCC:-"$ROOT/build/cycc"}
[ -x "$CC" ] || { echo "SKIP: embed_build: no compiler at $CC"; exit 77; }
W=$(mktemp -d) && [ -d "$W" ] || { echo "FAIL: embed_build: mktemp -d failed (TMPDIR=${TMPDIR:-/tmp})"; exit 1; }
trap 'rm -rf "$W"' EXIT
FAIL=0
fail() { echo "  FAIL: $*"; FAIL=$((FAIL + 1)); }
"$CC" < cbt/cyrius.cyr > "$W/cyrius" 2> "$W/build.err" || { echo "FAIL: embed_build: cbt/cyrius.cyr does not build"; tail -3 "$W/build.err"; exit 1; }
chmod +x "$W/cyrius"
mkdir -p "$W/home/bin"; cp "$CC" "$W/home/bin/cycc"
P="$W/p"
mkdir -p "$P/data" "$P/src" "$P/tests"
cp -R "$ROOT/lib" "$P/lib"
cli() { ( cd "$P" && env -u CYRIUS_DCE -u CYRIUS_DEFINES CYRIUS_HOME="$W/home" CYRIUS_RESOLVED=1 "$W/cyrius" "$@" ); }
# mf <entry> <[embed] lines...> — a manifest with no [package] version
mf() { e=$1; shift; { printf '[build]\nentry = "%s"\noutput = "build/main"\ndefines = ["FOO"]\n[embed]\n' "$e"; for l in "$@"; do printf '%s\n' "$l"; done; } > "$P/cyrius.cyml"; }
# build, then run build/main with stdout to $W/got; rc of the run in $run
br() { rm -rf "$P/build" "$W/got"; brc=0; cli build > "$W/b.out" 2>&1 || brc=$?; run=x; [ "$brc" = 0 ] && { run=0; "$P/build/main" > "$W/got" || run=$?; }; }

# ── axis 1 / 2: text, binary, empty ──────────────────────────────────────────────────────
x=$FAIL
printf 'a "quoted" \\ back\\slash\r\n\ttabbed\n#ifdef FOO\n#@srcline\n#@file evil.cyr\ninclude "x"\nFOO is defined\nh\303\251llo w\303\266rld \342\202\254\n' > "$P/data/t.txt"
i=0; while [ $i -lt 256 ]; do printf "\\$(printf '%03o' $i)"; i=$((i + 1)); done > "$P/data/b.bin"
: > "$P/data/e.bin"
[ "$(wc -c < "$P/data/b.bin" | tr -d ' ')" = 256 ] || fail "axis 2: the 256-value fixture is $(wc -c < "$P/data/b.bin") bytes"
printf 'syscall(1, 1, T(), T_len());\nsyscall(1, 1, B(), B_len());\nsyscall(60, E_len());\n' > "$P/main.cyr"
mf main.cyr 'T = "data/t.txt"' 'B = "data/b.bin"' 'E = "data/e.bin"'
br
cat "$P/data/t.txt" "$P/data/b.bin" > "$W/want"
if [ "$brc" != 0 ]; then fail "axes 1-2: the build failed (exit $brc): $(grep -E 'error|warning: undefined' "$W/b.out" | head -2 | tr '\n' ' ')"
else
    cmp -s "$W/want" "$W/got" || fail "axes 1-2: the bytes did not round-trip ($(wc -c < "$W/got" | tr -d ' ') of $(wc -c < "$W/want" | tr -d ' '))"
    [ "$run" = 0 ] || fail "axis 2: the empty embed's E_len() is $run, not 0"
fi
[ "$FAIL" = "$x" ] && echo "  ok axes 1-2: quotes, backslashes, CR/LF, tabs, directive-shaped lines, a define name, UTF-8, all 256 byte values and an empty file round-trip"

# ── axis 3: line-neutral ─────────────────────────────────────────────────────────────────
x=$FAIL
printf 'var a = 1;\nvar b = 2;\nvar c = ;\n' > "$P/main.cyr"
br
[ "$brc" != 0 ] && grep -q '<source>:3:' "$W/b.out" || fail "axis 3: an error on the entry's line 3 is not reported at <source>:3: $(grep error "$W/b.out" | head -1)"
[ "$FAIL" = "$x" ] && echo "  ok axis 3: the prelude is line-neutral (<source>:3)"

# ── axis 4: freshness ────────────────────────────────────────────────────────────────────
x=$FAIL
printf 'syscall(1, 1, T(), T_len());\nsyscall(60, 0);\n' > "$P/main.cyr"
mf main.cyr 'T = "data/f.txt"'
printf 'first\n' > "$P/data/f.txt"; br
cmp -s "$P/data/f.txt" "$W/got" || fail "axis 4: the first build did not carry the file"
printf 'second, longer\n' > "$P/data/f.txt"; br
cmp -s "$P/data/f.txt" "$W/got" || fail "axis 4: after editing the data file the rebuild still carries old bytes: $(cat "$W/got" 2>/dev/null)"
[ "$FAIL" = "$x" ] && echo "  ok axis 4: an edited data file is in the next build, with no generator step"

# ── axis 5: cyrius test ──────────────────────────────────────────────────────────────────
x=$FAIL
printf 'abc' > "$P/data/s.txt"
mf main.cyr 'S = "data/s.txt"'
printf 'if (S_len() == 3) { if (load8(S() + 2) == 99) { syscall(60, 0); } }\nsyscall(60, 1);\n' > "$P/tests/embed.tcyr"
rc=0; cli test tests/embed.tcyr > "$W/t.out" 2>&1 || rc=$?
[ "$rc" = 0 ] || fail "axis 5: cyrius test of a .tcyr reading the embed exited $rc: $(grep -E 'error|FAIL' "$W/t.out" | head -2 | tr '\n' ' ')"
[ "$FAIL" = "$x" ] && echo "  ok axis 5: cyrius test compiles the embed into a .tcyr"

# ── axis 6: 2 MB + stdlib + 3,000 literals, and its cost ─────────────────────────────────
x=$FAIL
head -c 2000000 /dev/urandom > "$P/data/big.bin"
{ for m in string fmt alloc io vec str args fs process syscalls; do printf 'include "lib/%s.cyr"\n' "$m"; done
  printf 'alloc_init();\nsyscall(1, 1, BIG(), BIG_len());\n'
  i=0; while [ $i -lt 3000 ]; do printf 'var s%d = "small literal %d";\n' $i $i; i=$((i + 1)); done; } > "$W/body"
{ cat "$W/body"; printf 'syscall(60, 0);\n'; } > "$P/big.cyr"
# the baseline: the same bytes as a hand-written module included LAST (generated here, with od —
# the same escaping, so the two compiles lex the same literal)
{ printf 'fn BIG(): i64 {\n    return "'
  od -An -v -tu1 "$P/data/big.bin" | tr -s ' \n' '\n\n' | awk 'NF { c = $1 + 0
      if (c == 34) printf "\\\""; else if (c == 92) printf "\\\\"; else if (c >= 32 && c <= 126) printf "%c", c; else printf "\\x%02x", c }'
  printf '";\n}\nfn BIG_len(): i64 { return 2000000; }\n'; } > "$P/big_mod.cyr"
{ cat "$W/body"; printf 'include "big_mod.cyr"\nsyscall(60, 0);\n'; } > "$P/base.cyr"
printf '[build]\nentry = "base.cyr"\noutput = "build/main"\n' > "$P/cyrius.cyml"
t0=$(date +%s%N); br; t1=$(date +%s%N)
base_ms=$(( (t1 - t0) / 1000000 ))
cmp -s "$P/data/big.bin" "$W/got" || fail "axis 6: the hand-written baseline does not round-trip (exit $brc) — the comparison would be meaningless"
mf big.cyr 'BIG = "data/big.bin"'
t0=$(date +%s%N); br; t1=$(date +%s%N)
emb_ms=$(( (t1 - t0) / 1000000 ))
cmp -s "$P/data/big.bin" "$W/got" || fail "axis 6: the 2,000,000-byte embed does not round-trip (exit $brc): $(grep -E 'error' "$W/b.out" | head -1)"
[ "$emb_ms" -lt $((2 * base_ms + 200)) ] || fail "axis 6: [embed] build took ${emb_ms} ms, the same bytes included last ${base_ms} ms — over 2x: the embed sits FIRST in the pool, so cycc's literal interning is paying for it (B0b)"
[ "$FAIL" = "$x" ] && echo "  ok axis 6: 2,000,000 B + stdlib + 3,000 literals round-trips; ${emb_ms} ms vs ${base_ms} ms hand-written-last"

# ── axis 7: the per-file cap compiles ────────────────────────────────────────────────────
x=$FAIL
head -c 2097150 /dev/zero | tr '\0' 'a' > "$P/data/cap.txt"
printf 'if (CAP_len() == 2097150) { if (load8(CAP() + 2097149) == 97) { if (load8(CAP() + 2097150) == 0) { syscall(60, 0); } } }\nsyscall(60, 1);\n' > "$P/cap.cyr"
printf '[build]\nentry = "cap.cyr"\noutput = "build/main"\n[embed]\nCAP = "data/cap.txt"\n' > "$P/cyrius.cyml"
br
[ "$brc" = 0 ] && [ "$run" = 0 ] || fail "axis 7: a 2,097,150-byte embed (cbt's per-file cap) does not compile and check out (build $brc, run $run): $(grep -E 'error' "$W/b.out" | head -1) — cbt's cap and cycc's pool disagree"
[ "$FAIL" = "$x" ] && echo "  ok axis 7: a 2,097,150-byte embed — the per-file cap — compiles, length and NUL right"

# ── axis 8: collisions ───────────────────────────────────────────────────────────────────
x=$FAIL
ln_reset=$(grep -n '^fn alloc_reset(): i64' "$P/lib/alloc.cyr" | cut -d: -f1)
ln_alloc=$(grep -n '^fn alloc(size): i64' "$P/lib/alloc.cyr" | cut -d: -f1)
[ -n "$ln_reset" ] && [ -n "$ln_alloc" ] || fail "axis 8: lib/alloc.cyr no longer has fn alloc_reset() / fn alloc(size) — re-pick the collision fixtures"
printf 'include "lib/alloc.cyr"\nalloc_init();\nsyscall(60, alloc_reset_len());\n' > "$P/main.cyr"
mf main.cyr 'alloc_reset = "data/s.txt"'
br
[ "$brc" = 0 ] && [ "$run" = 3 ] || fail "axis 8 same arity: the build failed or alloc_reset_len() is not 3 (build $brc, run $run)"
grep -q "warning:lib/alloc.cyr:$ln_reset:1: duplicate fn 'alloc_reset'" "$W/b.out" || fail "axis 8 same arity: no duplicate-fn warning at lib/alloc.cyr:$ln_reset: $(grep -E 'warn|error' "$W/b.out" | head -1)"
printf 'include "lib/alloc.cyr"\nalloc_init();\nsyscall(60, 0);\n' > "$P/main.cyr"
mf main.cyr 'alloc = "data/s.txt"'
br
[ "$brc" != 0 ] || fail "axis 8 arity: an embed named alloc (arity 0 against alloc(size)) built"
grep -q "error:lib/alloc.cyr:$ln_alloc:1: duplicate fn 'alloc' disagrees about arity" "$W/b.out" || fail "axis 8 arity: no arity-mismatch error at lib/alloc.cyr:$ln_alloc: $(grep -E 'error' "$W/b.out" | head -1)"
printf 'fn other(): i64 { return load8(GREET() + 2); }\n' > "$P/src/other.cyr"
printf 'include "src/other.cyr"\nsyscall(60, other());\n' > "$P/main.cyr"
mf main.cyr 'GREET = "data/s.txt"'
br
[ "$brc" = 0 ] && [ "$run" = 99 ] || fail "axis 8 other file: an included file calling GREET() did not get the bytes (build $brc, run $run, want 99)"
[ "$FAIL" = "$x" ] && echo "  ok axis 8: same-arity collision warns at the stdlib line, arity mismatch errors naming lib/alloc.cyr, another file calls NAME()"

[ "$FAIL" = 0 ] || { echo "FAIL: embed_build ($FAIL)"; exit 1; }
echo "PASS: embed_build"
