#!/bin/sh
# install_pillars_ship_the_checksum.sh — v6.6.6 (bite 26a). A gate that ships a RELEASE
# TARBALL to another machine and installs it there ships the `.sha256` sidecar with it, and
# REQUIRES the sidecar on the far side.
#
# ⛔ THE DEFECT (found at 67ea9c17). `_cross_os_selfhost()` in cbt/commands.cyr carries the
# two macOS install pillars inline — the ecb (Apple Silicon) arm added at v6.0.38 and the
# ach (Intel) arm at v6.4.59. Both built the real release tarball, `scp`'d it to the Mac and
# ran the REAL `scripts/install.sh` against it with `CYRIUS_INSTALL_TARBALL=…`. Neither ever
# sent a checksum. install.sh's local-tarball hook verifies fail-closed **only if a sidecar
# sits beside the tarball** (the CVE-21 branch); with no sidecar it copies the file and
# installs it. So the two gates whose whole job is "the published artifact installs on a
# real Mac" had never once verified that the artifact arrived intact, and the Intel-Mac arm
# has verified a hash on NO release since it was added. The tarball builders have ALWAYS
# written the sidecar (`sha256sum "$STAGE.tar.gz" > "$STAGE.tar.gz.sha256"`); the file was
# sitting in the output directory and nothing copied it.
#
# ⚠ THE REMOTE `[ -f …sha256 ]` IS PART OF THE FIX, not decoration. Because install.sh
# verifies only when the sidecar is present, an `scp` that silently dropped it would put the
# arm straight back on the unverified path with everything still green. The far side must
# refuse to start without it.
#
# AXES
#   1. STATIC over cbt/*.cyr: every `scp` that names a release tarball names the matching
#      `.sha256` in the SAME scp (sidecars counted separately from tarballs, so a sidecar
#      cannot be mistaken for the artifact). Floor: at least 2 such scp sites. The detector
#      is self-tested on both shapes.
#   2. STATIC: every pillar that runs install.sh with `CYRIUS_INSTALL_TARBALL=` first tests
#      that the sidecar is THERE — the two in `cbt/*.cyr` (same-line, inside the remote
#      command string) and the two `run: |` blocks in `.github/workflows/ci.yml` (the test a
#      line of its own above it). Floor: 4 sites, scan self-tested on 4 shapes.
#   3. BEHAVIOURAL, and the axis that makes axis 1 more than a string check: the REAL
#      `scripts/install.sh`, in a throwaway HOME + CYRIUS_HOME, over a locally built
#      tarball. (a) correct sidecar -> it says the checksum verified; (b) ONE BYTE appended
#      and the sidecar present -> it exits non-zero saying `checksum mismatch`, before it
#      unpacks anything; (c) the SAME tampered tarball with NO sidecar -> it never mentions
#      a checksum and walks straight past into the unpack. (c) is the measurement of what
#      the pillars were doing. Expected values are computed a different way from install.sh's
#      report: the sidecar is generated by `sha256sum` here and the tamper is a byte this
#      gate appends. "Before it unpacks anything" is DIFFERENTIAL — (a) and (c) both reach
#      the unpack and must show it, (b) must not — so the claim rests on a marker the gate
#      has just watched two other runs produce, not on one grep that could be unreachable.
#   4. STATIC, anti-drift on the other end: both macOS tarball builders must still WRITE the
#      sidecar and copy it into OUT_DIR — an scp naming a file the builder stopped producing
#      would fail on the Mac, far from the cause.
#
# MUTATION LEDGER (measured 6.6.6, each in a scratch copy of the tree):
#   a. cbt/commands.cyr as of 5a791030 (both pillars)      -> axis 1 FAIL (2 scp sites, 0
#                                                             sidecars) + axis 2 FAIL (2 sites)
#   b. the sidecar dropped from the ecb scp only           -> axis 1 FAIL (1 site)
#   c. the remote `[ -f …sha256 ]` dropped from ach only   -> axis 2 FAIL (1 site)
#   d. build-macos-arm64-tarball.sh's sidecar write removed-> axis 4 FAIL
#   e. install.sh's local-sidecar verify branch removed    -> axis 3 FAIL (a tampered tarball
#                                                             installs, rc 0 through the check)
#   f. the axis-1 detector's tarball arm disabled          -> axis 1 self-test FAIL
#   g. (bite 26 review) install.sh's local-sidecar         -> axis 3(b) FAIL, AND NOTHING ELSE —
#      MISMATCH downgraded from `err` to `warn … continuing   "install.sh reached the UNPACK for
#      anyway" (the pre-CVE-21 advisory shape). The check      a tarball whose checksum did not
#      still runs and still reports the mismatch; it just      match". The `no bin/` grep this
#      no longer stops the install.                            assertion replaced caught none of
#                                                              it — see the axis-3 note.
#   h. (bite 26 review) the `test -f "$TARBALL.sha256"`    -> axis 2 FAIL (naming
#      dropped from the macos-14 ci.yml pillar only,          .github/workflows/ci.yml:<line>,
#      its explanatory COMMENT left standing                  3 of 4 guarded). ⚠ The first cut
#                                                             of the window scan PASSED this —
#                                                             it matched any `.sha256` in the
#                                                             preceding lines, including the
#                                                             comment. It now requires a real
#                                                             `test -f` / `[ -f` and ignores
#                                                             whole-line comments.
# Real tree -> PASS.
#
# ⚠ NOT COVERED, and said plainly rather than implied — this enumeration is what a future
# reader will trust, so it is the COMPLETE list. `grep -rn CYRIUS_INSTALL_TARBALL` finds five
# live pillars. Four are covered here: `cbt/commands.cyr` ×2 (axes 1 + 2) and
# `.github/workflows/ci.yml` ×2 (axis 2 — they take their tarball from the artifact store,
# not an scp, so axis 1 does not apply to them). The fifth,
# `scripts/cross-os-selfhost.sh`'s `ecb-install` arm, and `scripts/cass-install-gate.sh`
# beside it, have the SAME shape and are NOT fixed by this bite — they belong to a parallel
# lane (bite 25a) that was not in this checkout, so nothing here was narrowed to compensate.
# If that lane's `install_gates_ship_the_checksum.sh` lands, its `scripts/*.sh` sweep and this
# gate's sweep are complementary halves of one claim; neither covers the other.
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT" || exit 2
D=$(mktemp -d) && [ -d "$D" ] || { echo "FAIL: install_pillars_ship_the_checksum: mktemp -d failed (TMPDIR=${TMPDIR:-/tmp})"; exit 1; }
trap 'rm -rf "$D"' EXIT
FAIL=0
fail() { echo "FAIL: $*"; FAIL=1; }
ulimit -c 0 2>/dev/null
command -v sha256sum >/dev/null 2>&1 || { echo "FAIL: sha256sum not found — this gate computes the expected digest itself"; exit 1; }

# ── axis 1: every scp of a release tarball carries its sidecar ───────────────
# Prints "<file>|<tarballs>|<sidecars>" per scp command that names a .tar.gz.
cat > "$D/scp.awk" <<'AWK'
{
    line = $0
    sub(/^[ \t]*#.*/, "", line)
    s = line
    while ((i = index(s, "scp ")) > 0) {
        s = substr(s, i)
        e = length(s) + 1
        for (k = 1; k <= length(s); k++) { c = substr(s, k, 1); if (c == ";" || c == "\"") { e = k; break } }
        seg = substr(s, 1, e - 1)
        s = substr(s, e + 1)
        if (seg ~ /\.tar\.gz/) {
            t = seg; nsc = gsub(/\.tar\.gz\.sha256/, "", t)
            u = seg; nall = gsub(/\.tar\.gz/, "", u)
            printf "%s|%d|%d\n", FILE, nall - nsc, nsc
        }
    }
}
AWK
_scp_sites() { awk -v FILE="$2" -f "$D/scp.awk" "$1"; }
mkdir -p "$D/fx"
printf '    var x = "…; scp -q scripts/install.sh $_T/dist/cyrius-$V-aarch64-macos.tar.gz ecb:~/; ssh …";\n' > "$D/fx/bad.cyr"
printf '    var x = "…; scp -q scripts/install.sh $_T/dist/cyrius-$V-aarch64-macos.tar.gz $_T/dist/cyrius-$V-aarch64-macos.tar.gz.sha256 ecb:~/; ssh …";\n' > "$D/fx/good.cyr"
printf '    # scp -q $_T/dist/cyrius-$V-aarch64-macos.tar.gz ecb:~/ in a comment is not a site\n' > "$D/fx/cmt.cyr"
a1=0
[ "$(_scp_sites "$D/fx/bad.cyr" x)" = 'x|1|0' ]  || { fail "axis 1 self-test: an scp with no sidecar is not seen as 1 tarball / 0 sidecars: '$(_scp_sites "$D/fx/bad.cyr" x)'"; a1=1; }
[ "$(_scp_sites "$D/fx/good.cyr" x)" = 'x|1|1' ] || { fail "axis 1 self-test: an scp WITH a sidecar is miscounted: '$(_scp_sites "$D/fx/good.cyr" x)'"; a1=1; }
[ -z "$(_scp_sites "$D/fx/cmt.cyr" x)" ]         || { fail "axis 1 self-test: a commented-out scp was counted"; a1=1; }
: > "$D/sites"
for f in $(ls cbt/*.cyr | LC_ALL=C sort); do _scp_sites "$f" "$f" >> "$D/sites"; done
nsite=$(wc -l < "$D/sites" | tr -d ' ')
[ "$nsite" -ge 2 ] || { fail "axis 1: found $nsite scp-a-release-tarball site(s) in cbt/ (floor 2 — the ecb and ach install pillars) — the scan read nothing, or a pillar was deleted"; a1=1; }
while IFS='|' read -r f ntar nsc; do
    [ -n "$f" ] || continue
    [ "$nsc" -ge "$ntar" ] || { fail "axis 1: $f ships $ntar release tarball(s) with only $nsc .sha256 sidecar(s) — install.sh verifies a local tarball ONLY when a sidecar sits beside it, so this pillar installs unverified"; a1=1; }
done < "$D/sites"
[ "$a1" = 0 ] && echo "  ok: axis 1: $nsite scp-a-release-tarball site(s) in cbt/, every one also shipping its .sha256 (detector self-tested on 3 shapes)"

# ── axis 2: the far side REQUIRES the sidecar before it installs ─────────────
# FOUR pillars, two shapes, one rule (bite 26 review widened this from cbt/ alone — the two
# CI ones were absent from the sweep AND from the "not covered" note, which is what a future
# reader would have trusted). In cbt/*.cyr a pillar is ONE remote command string, so the test
# sits on the same line. In .github/workflows/ci.yml it is a `run: |` block — the macos-14
# funcgate and the self-hosted Intel-Mac (ach) funcgate, each installing a tarball downloaded
# from the artifact store onto another machine — so the test is a line of its own above it,
# required within the preceding 10 lines. Both were fail-open: the sidecar reaches the runner
# only because upload-artifact takes the whole OUT_DIR and build-macos-*-tarball.sh puts it
# there, and NOTHING required it.
a2=0
_pillar_scan() {   # <file> -> "<file>:<line>:<0|1 guarded>" per live pillar
    awk -v F="$1" '
        /CYRIUS_INSTALL_TARBALL=/ {
            c = $0; sub(/^[ \t]*#/, "#", c)
            if (c ~ /^#/) { prev[NR] = $0; next }              # a commented-out pillar is not a site
            g = ($0 ~ /\.tar\.gz\.sha256[ \t]*\]/) ? 1 : 0     # same-line test (the cbt shape)
            if (g == 0) {                                      # …or a test in the 10 lines above (the YAML shape)
                s = (NR > 10) ? NR - 10 : 1
                for (i = s; i < NR; i++) if (prev[i] ~ /\.sha256/ && prev[i] ~ /(test -[fs]|\[ -[fs])/) g = 1
            }
            printf "%s:%d:%d\n", F, NR, g
        }
        # A whole-line comment is NOT a guard, and the window test above requires a real file
        # TEST beside the name. The first cut matched any .sha256 in the preceding lines, so
        # deleting the test -f from a pillar left the explanatory COMMENT above it standing
        # and the gate still read green (measured; that is ledger row h).
        { c = $0; sub(/^[ \t]*/, "", c); prev[NR] = (substr(c, 1, 1) == "#") ? "" : $0 }
    ' "$1"
}
: > "$D/pillars"
for f in $(ls cbt/*.cyr | LC_ALL=C sort) .github/workflows/ci.yml; do
    [ -f "$f" ] || { fail "axis 2: $f is missing — an install pillar's file is gone"; a2=1; continue; }
    _pillar_scan "$f" >> "$D/pillars"
done
# self-test, so the scan cannot pass by seeing nothing or by calling everything guarded
printf 'x CYRIUS_INSTALL_TARBALL=$T sh install.sh\n' > "$D/fx/p_bad.yml"
printf 'test -f "$T.sha256" || exit 1\nCYRIUS_INSTALL_TARBALL=$T sh install.sh\n' > "$D/fx/p_ok.yml"
printf "ssh h '[ -f \$HOME/c.tar.gz.sha256 ] && CYRIUS_INSTALL_TARBALL=\$HOME/c.tar.gz sh install.sh'\n" > "$D/fx/p_inline.cyr"
# a COMMENT naming the sidecar is not a guard — this is how ledger row h passed the first cut
printf '# REQUIRE the .sha256 sidecar before installing\nCYRIUS_INSTALL_TARBALL=$T sh install.sh\n' > "$D/fx/p_cmt.yml"
[ "$(_pillar_scan "$D/fx/p_bad.yml")" = "$D/fx/p_bad.yml:1:0" ]    || { fail "axis 2 self-test: an unguarded pillar is not seen as unguarded: '$(_pillar_scan "$D/fx/p_bad.yml")'"; a2=1; }
[ "$(_pillar_scan "$D/fx/p_ok.yml")" = "$D/fx/p_ok.yml:2:1" ]      || { fail "axis 2 self-test: a pillar guarded a few lines above is not seen as guarded: '$(_pillar_scan "$D/fx/p_ok.yml")'"; a2=1; }
[ "$(_pillar_scan "$D/fx/p_inline.cyr")" = "$D/fx/p_inline.cyr:1:1" ] || { fail "axis 2 self-test: a pillar guarded on its own line is not seen as guarded: '$(_pillar_scan "$D/fx/p_inline.cyr")'"; a2=1; }
[ "$(_pillar_scan "$D/fx/p_cmt.yml")" = "$D/fx/p_cmt.yml:2:0" ]    || { fail "axis 2 self-test: a COMMENT naming the sidecar was accepted as the guard: '$(_pillar_scan "$D/fx/p_cmt.yml")'"; a2=1; }
ninst=$(grep -c . "$D/pillars"); ninst=${ninst:-0}
[ "$ninst" -ge 4 ] || { fail "axis 2: found $ninst install-pillar line(s) (floor 4 — ecb + ach in cbt/, macos-14 + ach in ci.yml) — the scan read nothing, or a pillar was deleted"; a2=1; }
nguard=0
while IFS=: read -r f ln g; do
    [ -n "$f" ] || continue
    if [ "$g" = 1 ]; then nguard=$((nguard + 1)); else
        fail "axis 2: the install pillar at $f:$ln runs install.sh without first testing that the .sha256 is there — install.sh verifies a local tarball ONLY when a sidecar sits beside it, so a dropped or unshipped sidecar installs unverified with everything still green:"
        echo "      $(sed -n "${ln}p" "$f" | cut -c1-120)…"; a2=1
    fi
done < "$D/pillars"
[ "$nguard" -ge 4 ] || { fail "axis 2: only $nguard install pillar(s) test for the sidecar (floor 4)"; a2=1; }
[ "$a2" = 0 ] && echo "  ok: axis 2: all $ninst install pillar(s) — 2 in cbt/, 2 in ci.yml — refuse to start unless the .sha256 is there (scan self-tested on 4 shapes)"

# ── axis 3: what the sidecar actually buys, measured against the REAL install.sh ──
# A throwaway HOME and CYRIUS_HOME: nothing here touches the live store.
a3=0
V=9.9.9
mkdir -p "$D/i/home" "$D/i/stage/cyrius-$V-aarch64-macos/bin" "$D/i/dist"
printf '#!/bin/sh\nexit 0\n' > "$D/i/stage/cyrius-$V-aarch64-macos/bin/cyrius"
chmod +x "$D/i/stage/cyrius-$V-aarch64-macos/bin/cyrius"
( cd "$D/i/stage" && tar czf "$D/i/dist/cyrius-$V-aarch64-macos.tar.gz" "cyrius-$V-aarch64-macos" ) \
  || { echo "FAIL: axis 3: cannot build the fixture tarball"; exit 1; }
( cd "$D/i/dist" && sha256sum "cyrius-$V-aarch64-macos.tar.gz" > "cyrius-$V-aarch64-macos.tar.gz.sha256" ) \
  || { echo "FAIL: axis 3: cannot write the fixture sidecar"; exit 1; }
# the tampered twin: the SAME bytes plus one, with a sidecar carrying the ORIGINAL digest
cp "$D/i/dist/cyrius-$V-aarch64-macos.tar.gz" "$D/i/dist/tampered.tar.gz"
sed "s/cyrius-$V-aarch64-macos\.tar\.gz/tampered.tar.gz/" "$D/i/dist/cyrius-$V-aarch64-macos.tar.gz.sha256" > "$D/i/dist/tampered.tar.gz.sha256"
printf 'X' >> "$D/i/dist/tampered.tar.gz"
cp "$D/i/dist/tampered.tar.gz" "$D/i/dist/tampered_nosidecar.tar.gz"   # same bytes, no sidecar
_install() {  # _install <tarball> <home-suffix> -> output in $D/i/<suffix>.out, rc echoed
    rc=0
    ( HOME="$D/i/home" CYRIUS_VERSION="$V" CYRIUS_HOME="$D/i/home/.c$2" \
      CYRIUS_INSTALL_TARBALL="$1" sh scripts/install.sh ) > "$D/i/$2.out" 2>&1 || rc=$?
    echo "$rc"
}
# "before it unpacks anything" is measured DIFFERENTIALLY, against the runs that DO reach the
# unpack — never by a single grep for one line the refusing run could not print either way.
# (bite 26 review: this used to grep B for `no bin/`, which install.sh emits only AFTER an
# unpack whose tree has no bin/ — the gate's fixture tarball HAS one, so on no run could that
# string appear and the assertion asserted nothing.) The unpack stage speaks for itself:
# tar/gzip's own diagnostics on a corrupt archive, or install.sh's post-extract verdicts.
_unpacked() { grep -qE '^(tar|gzip):|no bin/|binaries installed|standard library installed' "$1"; }
rcA=$(_install "$D/i/dist/cyrius-$V-aarch64-macos.tar.gz" A)
grep -q 'checksum verified (local sidecar)' "$D/i/A.out" \
  || { fail "axis 3(a): install.sh did not verify an intact tarball against its sidecar:"; sed 's/^/      /' "$D/i/A.out" | tail -3; a3=1; }
grep -q 'checksum mismatch' "$D/i/A.out" && { fail "axis 3(a): install.sh reported a mismatch for a tarball that matches its sidecar"; a3=1; }
_unpacked "$D/i/A.out" \
  || { fail "axis 3(a): a VERIFIED tarball did not reach the unpack — the 'before unpacking' marker is unreachable, so 3(b) would assert nothing:"; sed 's/^/      /' "$D/i/A.out" | tail -3; a3=1; }
rcB=$(_install "$D/i/dist/tampered.tar.gz" B)
[ "$rcB" -ne 0 ] || { fail "axis 3(b): install.sh accepted a tarball ONE BYTE longer than its sidecar says (rc 0)"; a3=1; }
grep -q 'checksum mismatch' "$D/i/B.out" || { fail "axis 3(b): the refusal does not say the checksum did not match:"; sed 's/^/      /' "$D/i/B.out" | tail -3; a3=1; }
_unpacked "$D/i/B.out" && { fail "axis 3(b): install.sh reached the UNPACK for a tarball whose checksum did not match — the refusal is not before it opens the archive:"; sed 's/^/      /' "$D/i/B.out" | tail -3; a3=1; }
rcC=$(_install "$D/i/dist/tampered_nosidecar.tar.gz" C)
if grep -q 'checksum' "$D/i/C.out"; then
    fail "axis 3(c): the fixture is wrong — install.sh mentioned a checksum for a tarball with NO sidecar, so the pillars were not actually unverified"; a3=1
fi
grep -q 'installing from local tarball' "$D/i/C.out" \
  || { fail "axis 3(c): install.sh did not take the local-tarball path at all:"; sed 's/^/      /' "$D/i/C.out" | tail -3; a3=1; }
_unpacked "$D/i/C.out" \
  || { fail "axis 3(c): with NO sidecar install.sh did not walk into the unpack — the SAME bytes B refused, so this is the control that makes 3(b)'s absence mean something:"; sed 's/^/      /' "$D/i/C.out" | tail -3; a3=1; }
[ "$a3" = 0 ] && echo "  ok: axis 3: install.sh verifies a local tarball against its sidecar (rc $rcA), refuses a 1-byte tamper before unpacking (rc $rcB), and with NO sidecar never checks at all (rc $rcC) — which is what the pillars were doing"

# ── axis 4: the builders still produce the sidecar the scp names ─────────────
a4=0
for b in scripts/build-macos-arm64-tarball.sh scripts/build-macos-x86-tarball.sh; do
    [ -f "$b" ] || { fail "axis 4: $b is missing — a pillar scp names a tarball nothing builds"; a4=1; continue; }
    grep -q 'sha256sum "\$STAGE.tar.gz" > "\$STAGE.tar.gz.sha256"' "$b" \
      || { fail "axis 4: $b no longer WRITES the .sha256 sidecar — the pillar scp would name a file that does not exist"; a4=1; }
    grep -qE '(cp|mv) "\$WORK/\$STAGE\.tar\.gz" "\$WORK/\$STAGE\.tar\.gz\.sha256" "\$OUT_DIR/"' "$b" \
      || { fail "axis 4: $b no longer copies the sidecar into OUT_DIR — it exists only in the work dir the scp cannot reach"; a4=1; }
done
[ "$a4" = 0 ] && echo "  ok: axis 4: both macOS tarball builders write the .sha256 and land it in OUT_DIR beside the tarball"

if [ "$FAIL" != 0 ]; then echo "FAIL: install_pillars_ship_the_checksum"; exit 1; fi
echo "PASS install_pillars_ship_the_checksum (both macOS scp pillars ship the .sha256; all FOUR install pillars — 2 in cbt/, 2 in ci.yml — require it before they install; install.sh verifies it, refuses a 1-byte tamper before it unpacks anything, and without it checks nothing)"
