#!/bin/sh
# install_pillars_ship_the_checksum.sh — v6.6.6 (bite 26a). A gate that ships a RELEASE
# TARBALL to another machine and installs it there ships the `.sha256` sidecar with it, and
# REQUIRES the sidecar on the far side.
#
# ⛔ THE DEFECT (found at 67ea9c17). `_cross_os_selfhost()` in cbt/commands.cyr carries the
# two macOS install pillars inline — the ecb (Apple Silicon) arm added at v6.0.38 and the
# ach (Intel) arm at v6.4.59. Both built the real release tarball, `scp`'d it to the Mac and
# ran the REAL `scripts/install.sh` against it with `CYRIUS_INSTALL_TARBALL=…`. Neither ever
# sent a checksum. install.sh's local-tarball hook verifies fail-closed **only if a sidecar
# sits beside the tarball** (the CVE-21 branch); with no sidecar it copies the file and
# installs it. So the two gates whose whole job is "the published artifact installs on a
# real Mac" had never once verified that the artifact arrived intact, and the Intel-Mac arm
# has verified a hash on NO release since it was added. The tarball builders have ALWAYS
# written the sidecar (`sha256sum "$STAGE.tar.gz" > "$STAGE.tar.gz.sha256"`); the file was
# sitting in the output directory and nothing copied it.
#
# ⚠ THE REMOTE `[ -f …sha256 ]` IS PART OF THE FIX, not decoration. Because install.sh
# verifies only when the sidecar is present, an `scp` that silently dropped it would put the
# arm straight back on the unverified path with everything still green. The far side must
# refuse to start without it.
#
# AXES
#   1. STATIC over cbt/*.cyr: every `scp` that names a release tarball names the matching
#      `.sha256` in the SAME scp (sidecars counted separately from tarballs, so a sidecar
#      cannot be mistaken for the artifact). Floor: at least 2 such scp sites. The detector
#      is self-tested on both shapes.
#   2. STATIC: every remote command that runs install.sh with `CYRIUS_INSTALL_TARBALL=`
#      first tests that the sidecar is THERE. Floor: at least 2 sites.
#   3. BEHAVIOURAL, and the axis that makes axis 1 more than a string check: the REAL
#      `scripts/install.sh`, in a throwaway HOME + CYRIUS_HOME, over a locally built
#      tarball. (a) correct sidecar -> it says the checksum verified; (b) ONE BYTE appended
#      and the sidecar present -> it exits non-zero saying `checksum mismatch`, before it
#      unpacks anything; (c) the SAME tampered tarball with NO sidecar -> it never mentions
#      a checksum and walks straight past into the unpack. (c) is the measurement of what
#      the pillars were doing. Expected values are computed a different way from install.sh's
#      report: the sidecar is generated by `sha256sum` here and the tamper is a byte this
#      gate appends.
#   4. STATIC, anti-drift on the other end: both macOS tarball builders must still WRITE the
#      sidecar and copy it into OUT_DIR — an scp naming a file the builder stopped producing
#      would fail on the Mac, far from the cause.
#
# MUTATION LEDGER (measured 6.6.6, each in a scratch copy of the tree):
#   a. cbt/commands.cyr as of 5a791030 (both pillars)      -> axis 1 FAIL (2 scp sites, 0
#                                                             sidecars) + axis 2 FAIL (2 sites)
#   b. the sidecar dropped from the ecb scp only           -> axis 1 FAIL (1 site)
#   c. the remote `[ -f …sha256 ]` dropped from ach only   -> axis 2 FAIL (1 site)
#   d. build-macos-arm64-tarball.sh's sidecar write removed-> axis 4 FAIL
#   e. install.sh's local-sidecar verify branch removed    -> axis 3 FAIL (a tampered tarball
#                                                             installs, rc 0 through the check)
#   f. the axis-1 detector's tarball arm disabled          -> axis 1 self-test FAIL
# Real tree -> PASS.
#
# ⚠ NOT COVERED, and said plainly rather than implied: `scripts/cross-os-selfhost.sh`'s
# `ecb-install` arm and `scripts/cass-install-gate.sh` have the SAME shape and are NOT fixed
# by this bite — they belong to a parallel lane (bite 25a) that was not in this checkout. If
# that lane's `install_gates_ship_the_checksum.sh` lands, its `scripts/*.sh` sweep and this
# gate's `cbt/*.cyr` sweep are complementary halves of one claim; neither covers the other.
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT" || exit 2
D=$(mktemp -d) && [ -d "$D" ] || { echo "FAIL: install_pillars_ship_the_checksum: mktemp -d failed (TMPDIR=${TMPDIR:-/tmp})"; exit 1; }
trap 'rm -rf "$D"' EXIT
FAIL=0
fail() { echo "FAIL: $*"; FAIL=1; }
ulimit -c 0 2>/dev/null
command -v sha256sum >/dev/null 2>&1 || { echo "FAIL: sha256sum not found — this gate computes the expected digest itself"; exit 1; }

# ── axis 1: every scp of a release tarball carries its sidecar ───────────────
# Prints "<file>|<tarballs>|<sidecars>" per scp command that names a .tar.gz.
cat > "$D/scp.awk" <<'AWK'
{
    line = $0
    sub(/^[ \t]*#.*/, "", line)
    s = line
    while ((i = index(s, "scp ")) > 0) {
        s = substr(s, i)
        e = length(s) + 1
        for (k = 1; k <= length(s); k++) { c = substr(s, k, 1); if (c == ";" || c == "\"") { e = k; break } }
        seg = substr(s, 1, e - 1)
        s = substr(s, e + 1)
        if (seg ~ /\.tar\.gz/) {
            t = seg; nsc = gsub(/\.tar\.gz\.sha256/, "", t)
            u = seg; nall = gsub(/\.tar\.gz/, "", u)
            printf "%s|%d|%d\n", FILE, nall - nsc, nsc
        }
    }
}
AWK
_scp_sites() { awk -v FILE="$2" -f "$D/scp.awk" "$1"; }
mkdir -p "$D/fx"
printf '    var x = "…; scp -q scripts/install.sh $_T/dist/cyrius-$V-aarch64-macos.tar.gz ecb:~/; ssh …";\n' > "$D/fx/bad.cyr"
printf '    var x = "…; scp -q scripts/install.sh $_T/dist/cyrius-$V-aarch64-macos.tar.gz $_T/dist/cyrius-$V-aarch64-macos.tar.gz.sha256 ecb:~/; ssh …";\n' > "$D/fx/good.cyr"
printf '    # scp -q $_T/dist/cyrius-$V-aarch64-macos.tar.gz ecb:~/ in a comment is not a site\n' > "$D/fx/cmt.cyr"
a1=0
[ "$(_scp_sites "$D/fx/bad.cyr" x)" = 'x|1|0' ]  || { fail "axis 1 self-test: an scp with no sidecar is not seen as 1 tarball / 0 sidecars: '$(_scp_sites "$D/fx/bad.cyr" x)'"; a1=1; }
[ "$(_scp_sites "$D/fx/good.cyr" x)" = 'x|1|1' ] || { fail "axis 1 self-test: an scp WITH a sidecar is miscounted: '$(_scp_sites "$D/fx/good.cyr" x)'"; a1=1; }
[ -z "$(_scp_sites "$D/fx/cmt.cyr" x)" ]         || { fail "axis 1 self-test: a commented-out scp was counted"; a1=1; }
: > "$D/sites"
for f in $(ls cbt/*.cyr | LC_ALL=C sort); do _scp_sites "$f" "$f" >> "$D/sites"; done
nsite=$(wc -l < "$D/sites" | tr -d ' ')
[ "$nsite" -ge 2 ] || { fail "axis 1: found $nsite scp-a-release-tarball site(s) in cbt/ (floor 2 — the ecb and ach install pillars) — the scan read nothing, or a pillar was deleted"; a1=1; }
while IFS='|' read -r f ntar nsc; do
    [ -n "$f" ] || continue
    [ "$nsc" -ge "$ntar" ] || { fail "axis 1: $f ships $ntar release tarball(s) with only $nsc .sha256 sidecar(s) — install.sh verifies a local tarball ONLY when a sidecar sits beside it, so this pillar installs unverified"; a1=1; }
done < "$D/sites"
[ "$a1" = 0 ] && echo "  ok: axis 1: $nsite scp-a-release-tarball site(s) in cbt/, every one also shipping its .sha256 (detector self-tested on 3 shapes)"

# ── axis 2: the far side REQUIRES the sidecar before it installs ─────────────
a2=0
ninst=$(grep -c 'CYRIUS_INSTALL_TARBALL=' cbt/*.cyr | awk -F: '{s += $2} END {print s+0}')
[ "$ninst" -ge 2 ] || { fail "axis 2: found $ninst install-pillar line(s) in cbt/ (floor 2)"; a2=1; }
nguard=0
grep -n 'CYRIUS_INSTALL_TARBALL=' cbt/*.cyr > "$D/pillars" 2>/dev/null
while IFS= read -r hit; do
    [ -n "$hit" ] || continue
    body=${hit#*:*:}
    case "$body" in
        [\ \t]*\#*) continue;;
    esac
    case "$body" in
        *'.tar.gz.sha256 ]'*) nguard=$((nguard + 1));;
        *) fail "axis 2: an install pillar runs install.sh without first testing that the .sha256 arrived — a dropped sidecar silently returns it to the unverified path:"
           echo "      $(echo "$hit" | cut -c1-120)…"; a2=1;;
    esac
done < "$D/pillars"
[ "$nguard" -ge 2 ] || { fail "axis 2: only $nguard install pillar(s) test for the sidecar (floor 2)"; a2=1; }
[ "$a2" = 0 ] && echo "  ok: axis 2: all $ninst install pillar(s) refuse to start unless the .sha256 is on the far side"

# ── axis 3: what the sidecar actually buys, measured against the REAL install.sh ──
# A throwaway HOME and CYRIUS_HOME: nothing here touches the live store.
a3=0
V=9.9.9
mkdir -p "$D/i/home" "$D/i/stage/cyrius-$V-aarch64-macos/bin" "$D/i/dist"
printf '#!/bin/sh\nexit 0\n' > "$D/i/stage/cyrius-$V-aarch64-macos/bin/cyrius"
chmod +x "$D/i/stage/cyrius-$V-aarch64-macos/bin/cyrius"
( cd "$D/i/stage" && tar czf "$D/i/dist/cyrius-$V-aarch64-macos.tar.gz" "cyrius-$V-aarch64-macos" ) \
  || { echo "FAIL: axis 3: cannot build the fixture tarball"; exit 1; }
( cd "$D/i/dist" && sha256sum "cyrius-$V-aarch64-macos.tar.gz" > "cyrius-$V-aarch64-macos.tar.gz.sha256" ) \
  || { echo "FAIL: axis 3: cannot write the fixture sidecar"; exit 1; }
# the tampered twin: the SAME bytes plus one, with a sidecar carrying the ORIGINAL digest
cp "$D/i/dist/cyrius-$V-aarch64-macos.tar.gz" "$D/i/dist/tampered.tar.gz"
sed "s/cyrius-$V-aarch64-macos\.tar\.gz/tampered.tar.gz/" "$D/i/dist/cyrius-$V-aarch64-macos.tar.gz.sha256" > "$D/i/dist/tampered.tar.gz.sha256"
printf 'X' >> "$D/i/dist/tampered.tar.gz"
cp "$D/i/dist/tampered.tar.gz" "$D/i/dist/tampered_nosidecar.tar.gz"   # same bytes, no sidecar
_install() {  # _install <tarball> <home-suffix> -> output in $D/i/<suffix>.out, rc echoed
    rc=0
    ( HOME="$D/i/home" CYRIUS_VERSION="$V" CYRIUS_HOME="$D/i/home/.c$2" \
      CYRIUS_INSTALL_TARBALL="$1" sh scripts/install.sh ) > "$D/i/$2.out" 2>&1 || rc=$?
    echo "$rc"
}
rcA=$(_install "$D/i/dist/cyrius-$V-aarch64-macos.tar.gz" A)
grep -q 'checksum verified (local sidecar)' "$D/i/A.out" \
  || { fail "axis 3(a): install.sh did not verify an intact tarball against its sidecar:"; sed 's/^/      /' "$D/i/A.out" | tail -3; a3=1; }
grep -q 'checksum mismatch' "$D/i/A.out" && { fail "axis 3(a): install.sh reported a mismatch for a tarball that matches its sidecar"; a3=1; }
rcB=$(_install "$D/i/dist/tampered.tar.gz" B)
[ "$rcB" -ne 0 ] || { fail "axis 3(b): install.sh accepted a tarball ONE BYTE longer than its sidecar says (rc 0)"; a3=1; }
grep -q 'checksum mismatch' "$D/i/B.out" || { fail "axis 3(b): the refusal does not say the checksum did not match:"; sed 's/^/      /' "$D/i/B.out" | tail -3; a3=1; }
grep -q 'no bin/' "$D/i/B.out" && { fail "axis 3(b): install.sh unpacked the tampered tarball before refusing it"; a3=1; }
rcC=$(_install "$D/i/dist/tampered_nosidecar.tar.gz" C)
if grep -q 'checksum' "$D/i/C.out"; then
    fail "axis 3(c): the fixture is wrong — install.sh mentioned a checksum for a tarball with NO sidecar, so the pillars were not actually unverified"; a3=1
fi
grep -q 'installing from local tarball' "$D/i/C.out" \
  || { fail "axis 3(c): install.sh did not take the local-tarball path at all:"; sed 's/^/      /' "$D/i/C.out" | tail -3; a3=1; }
[ "$a3" = 0 ] && echo "  ok: axis 3: install.sh verifies a local tarball against its sidecar (rc $rcA), refuses a 1-byte tamper before unpacking (rc $rcB), and with NO sidecar never checks at all (rc $rcC) — which is what the pillars were doing"

# ── axis 4: the builders still produce the sidecar the scp names ─────────────
a4=0
for b in scripts/build-macos-arm64-tarball.sh scripts/build-macos-x86-tarball.sh; do
    [ -f "$b" ] || { fail "axis 4: $b is missing — a pillar scp names a tarball nothing builds"; a4=1; continue; }
    grep -q 'sha256sum "\$STAGE.tar.gz" > "\$STAGE.tar.gz.sha256"' "$b" \
      || { fail "axis 4: $b no longer WRITES the .sha256 sidecar — the pillar scp would name a file that does not exist"; a4=1; }
    grep -qE '(cp|mv) "\$WORK/\$STAGE\.tar\.gz" "\$WORK/\$STAGE\.tar\.gz\.sha256" "\$OUT_DIR/"' "$b" \
      || { fail "axis 4: $b no longer copies the sidecar into OUT_DIR — it exists only in the work dir the scp cannot reach"; a4=1; }
done
[ "$a4" = 0 ] && echo "  ok: axis 4: both macOS tarball builders write the .sha256 and land it in OUT_DIR beside the tarball"

if [ "$FAIL" != 0 ]; then echo "FAIL: install_pillars_ship_the_checksum"; exit 1; fi
echo "PASS install_pillars_ship_the_checksum (both macOS install pillars ship the .sha256 and require it on the far side; install.sh verifies it, refuses a 1-byte tamper, and without it checks nothing)"
