#!/bin/sh
# pp_directive_inside_multiline_string.sh — v6.6.6 bite 4.
#
# A cyrius string literal may hold a RAW newline. The preprocessor's FOUR
# line-oriented passes (PP_PASS, PP_IFDEF_PASS, PP_REF_PASS and the `#host_only`
# scanner PP_IS_HOST_ONLY) decide "is this line a directive?" from the line's
# first non-space byte, and until 6.6.6 each reset
# its `in_string` flag at every newline "as a safety net", on the written premise
# that "cyrius source uses single-line strings". That premise was false —
# src/main.cyr and src/frontend/parse_expr.cyr both spell error messages with a
# literal LF inside the string — so a line sitting INSIDE a multi-line string was
# read as a fresh line of code and its directives were EXECUTED:
#
#   var s = "ab\n#ifdef NOPE\ncd\n#endif\nef";   →   the binary held ab\n\n\n\nef
#
# Silent: exit 0, no diagnostic, and the program's string data was simply not
# what the source said. Fixed by PP_LEXST (src/frontend/lex_pp.cyr), whose string
# state crosses newlines and which learned char literals so the old reset is not
# needed to bound a mis-read `"`.
#
# ⭐ EXPECTED IS DERIVED THE OTHER WAY ROUND. Each axis starts from a PAYLOAD
# file holding the exact bytes the string must contain; the .cyr source is
# GENERATED by wrapping that payload in quotes, and its byte count comes from
# `wc -c` on the payload. The actual is whatever the compiled binary writes to
# stdout. Nothing re-reads the generated source to decide what to expect.
#
# Axes:
#   1  #ifdef/#endif inside a multi-line string — the filed repro, byte for byte
#   2  #define inside a multi-line string keeps its line
#   3  #@file inside a multi-line string is not neutralised with a space
#   4  a continuation line starting `#ref ` compiles and keeps its bytes
#   5  the same string inside an INCLUDED file (PP_IFDEF_PASS's separate copy)
#   6  #define/#ifdef/#ifndef OUTSIDE a string still select branches
#   7  a `"` inside a # comment does not poison a later #ifdef (v5.9.34 guard)
#   8  a char literal holding `"` does not poison a later #ifdef
#   9  `#host_only` inside a multi-line string in an INCLUDED file is NOT an
#      annotation — a CYRIUS_KERNEL=1 build of it compiles (PP_IS_HOST_ONLY, the
#      fourth pass, which the first cut of this fix missed)
#  10  over-correction guard for 9: a REAL column-0 `#host_only` in an included
#      file is still recorded and still refuses the bare-metal build
#
# MUTATION LEDGER (2026-09-19, cycc 1,310,856 B). A scratch tree built with
# `git archive HEAD src bootstrap lib`, the fixed lex_pp.cyr overlaid, and the
# single line `if (c == 10) { bol = 1; } else { bol = 0; }` in PP_PASS and
# PP_IFDEF_PASS re-armed to also reset the string state:
#   mutated compiler → axes 1,2,3,5 FAIL (axis 1 prints ab\n\n\n\nef); the rest pass
#   PP_REF_PASS's `in_string` gate reverted → axis 4 FAILS (`cannot open #ref
#     file: ;`); every other axis passes
#   PP_LEXST's char-literal states (4/5) removed → axis 8 FAILS
#   PP_IS_HOST_ONLY's `in_string == 0` gate reverted → axis 9 FAILS
#     (`bare-metal build includes host-only module`); axis 10 still passes
#   real tree → 10/10 green
set -eu
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
CC=${CYRIUS_CC:-"$ROOT/build/cycc"}
D=$(mktemp -d) && [ -d "$D" ] || { echo "FAIL: mktemp"; exit 1; }
trap 'rm -rf "$D"' EXIT

pass=0; fail=0

# Build a program whose only string literal is exactly `$D/want.$1`, run it, and
# compare the bytes it writes with that payload file.
check_payload() {
    ax=$1; desc=$2
    n=$(wc -c < "$D/want.$ax" | tr -d ' ')
    {
        printf 'var s = "'
        cat "$D/want.$ax"
        printf '";\nsyscall(1, 1, s, %s);\nsyscall(60, 0);\n' "$n"
    } > "$D/p$ax.cyr"
    rc=0
    ( cd "$D" && cat "p$ax.cyr" | "$CC" > "p$ax.bin" 2> "p$ax.err" ) || rc=$?
    if [ "$rc" -ne 0 ]; then
        printf '  FAIL: axis %s (%s) did not compile: %s\n' \
            "$ax" "$desc" "$(grep -m1 error "$D/p$ax.err" | cut -c1-90)"
        fail=$((fail+1)); return 0
    fi
    if [ ! -s "$D/p$ax.bin" ]; then
        printf '  FAIL: axis %s (%s) produced an EMPTY binary\n' "$ax" "$desc"
        fail=$((fail+1)); return 0
    fi
    chmod +x "$D/p$ax.bin"
    ( ulimit -c 0; "$D/p$ax.bin" > "$D/p$ax.out" 2>/dev/null ) || true
    if cmp -s "$D/p$ax.out" "$D/want.$ax"; then
        printf '  ok: axis %s — %s (%s bytes intact)\n' "$ax" "$desc" "$n"
        pass=$((pass+1))
    else
        printf '  FAIL: axis %s — %s\n' "$ax" "$desc"
        printf '        want: %s\n' "$(od -c < "$D/want.$ax" | head -2 | tr '\n' '|')"
        printf '        got : %s\n' "$(od -c < "$D/p$ax.out" | head -2 | tr '\n' '|')"
        fail=$((fail+1))
    fi
    rm -f "$D/p$ax.bin"
}

# Run a self-contained program and compare its exit code.
check_exit() {
    ax=$1; want=$2; desc=$3; src=$4
    printf '%b' "$src" > "$D/e$ax.cyr"
    rc=0
    ( cd "$D" && cat "e$ax.cyr" | "$CC" > "e$ax.bin" 2> "e$ax.err" ) || rc=$?
    if [ "$rc" -ne 0 ]; then
        printf '  FAIL: axis %s (%s) did not compile: %s\n' \
            "$ax" "$desc" "$(grep -m1 error "$D/e$ax.err" | cut -c1-90)"
        fail=$((fail+1)); return 0
    fi
    if [ ! -s "$D/e$ax.bin" ]; then
        printf '  FAIL: axis %s (%s) produced an EMPTY binary\n' "$ax" "$desc"
        fail=$((fail+1)); return 0
    fi
    chmod +x "$D/e$ax.bin"
    got=0
    ( ulimit -c 0; "$D/e$ax.bin" ) || got=$?
    if [ "$got" = "$want" ]; then
        printf '  ok: axis %s — %s (exit=%s)\n' "$ax" "$desc" "$got"
        pass=$((pass+1))
    else
        printf '  FAIL: axis %s — %s: exit=%s, want %s\n' "$ax" "$desc" "$got" "$want"
        fail=$((fail+1))
    fi
    rm -f "$D/e$ax.bin"
}

# ── axis 1 — the filed repro, verbatim.
printf 'ab\n#ifdef NOPE\ncd\n#endif\nef' > "$D/want.1"
check_payload 1 '#ifdef/#endif inside a multi-line string'

# ── axis 2 — #define inside a multi-line string.
printf 'p\n#define FOO 9\nq' > "$D/want.2"
check_payload 2 '#define inside a multi-line string'

# ── axis 3 — #@file inside a multi-line string must NOT gain an injected space.
printf 'm\n#@file z\nn' > "$D/want.3"
check_payload 3 '#@file inside a multi-line string'

# ── axis 4 — `#ref ` at a continuation line's start, PP_REF_PASS's own copy.
# Written out longhand because the string's closing quote is part of the shape.
printf 'var s = "r\n#ref ";\nsyscall(1, 1, s, 7);\nsyscall(60, 0);\n' > "$D/p4.cyr"
printf 'r\n#ref ' > "$D/want.4"
rc4=0
( cd "$D" && cat p4.cyr | "$CC" > p4.bin 2> p4.err ) || rc4=$?
if [ "$rc4" -ne 0 ]; then
    printf '  FAIL: axis 4 (#ref at a continuation line) did not compile: %s\n' \
        "$(grep -m1 error "$D/p4.err" | cut -c1-90)"; fail=$((fail+1))
elif [ ! -s "$D/p4.bin" ]; then
    printf '  FAIL: axis 4 produced an EMPTY binary\n'; fail=$((fail+1))
else
    chmod +x "$D/p4.bin"
    ( ulimit -c 0; "$D/p4.bin" > "$D/p4.out" 2>/dev/null ) || true
    if cmp -s "$D/p4.out" "$D/want.4"; then
        printf '  ok: axis 4 — a continuation line starting `#ref ` is data\n'; pass=$((pass+1))
    else
        printf '  FAIL: axis 4 — got %s\n' "$(od -c < "$D/p4.out" | head -1)"; fail=$((fail+1))
    fi
    rm -f "$D/p4.bin"
fi

# ── axis 5 — the same string inside an INCLUDED file. PP_IFDEF_PASS carries its
# own copy of the machine and is the pass that sees included content, so a fix to
# PP_PASS alone would leave this half broken.
printf 'ab\n#ifdef NOPE\ncd\n#endif\nef' > "$D/want.5"
n5=$(wc -c < "$D/want.5" | tr -d ' ')
{ printf 'var s = "'; cat "$D/want.5"; printf '";\n'; } > "$D/inc5.cyr"
printf 'include "inc5.cyr"\nsyscall(1, 1, s, %s);\nsyscall(60, 0);\n' "$n5" > "$D/p5.cyr"
rc5=0
( cd "$D" && cat p5.cyr | "$CC" > p5.bin 2> p5.err ) || rc5=$?
if [ "$rc5" -ne 0 ]; then
    printf '  FAIL: axis 5 (multi-line string in an included file) did not compile: %s\n' \
        "$(grep -m1 error "$D/p5.err" | cut -c1-90)"; fail=$((fail+1))
elif [ ! -s "$D/p5.bin" ]; then
    printf '  FAIL: axis 5 produced an EMPTY binary\n'; fail=$((fail+1))
else
    chmod +x "$D/p5.bin"
    ( ulimit -c 0; "$D/p5.bin" > "$D/p5.out" 2>/dev/null ) || true
    if cmp -s "$D/p5.out" "$D/want.5"; then
        printf '  ok: axis 5 — multi-line string inside an included file (%s bytes intact)\n' "$n5"
        pass=$((pass+1))
    else
        printf '  FAIL: axis 5 — want %s got %s\n' \
            "$(od -c < "$D/want.5" | head -1)" "$(od -c < "$D/p5.out" | head -1)"; fail=$((fail+1))
    fi
    rm -f "$D/p5.bin"
fi

# ── axis 6 — over-correction guard: directives outside strings still fire.
check_exit 6 7 'directives OUTSIDE a string still select branches' \
'#define ON 1\n#ifdef ON\nvar a = 7;\n#endif\n#ifndef ON\nvar a = 9;\n#endif\nsyscall(60, a);\n'

# ── axis 7 — a `"` inside a # comment must not poison a later directive.
# This is the v5.9.34 vyakarana 1.0.2 case; it was what the newline reset was
# credited with bounding, and it is a real state now instead.
check_exit 7 5 'a quote inside a # comment does not poison a later #ifdef' \
'# a quote in this comment: "\n#define ON 1\n#ifdef ON\nvar a = 5;\n#endif\n#ifndef ON\nvar a = 6;\n#endif\nsyscall(60, a);\n'

# ── axis 8 — a char literal holding `"` must not poison a later directive.
# Removing the newline reset is only safe because PP_LEXST knows char literals;
# tests/fixtures/lint_lexical/escapes.cyr shows the shape is real source.
check_exit 8 4 'a char literal holding a quote does not poison a later #ifdef' \
"var q = '\\\"';\n#define ON 1\n#ifdef ON\nvar a = 4;\n#endif\n#ifndef ON\nvar a = 8;\n#endif\nsyscall(60, a);\n"

# ── axes 9 and 10 — PP_IS_HOST_ONLY, the FOURTH line-oriented pass. It scans a
# freshly-READ include for a column-0 `#host_only` and had no lexical state at
# all, so the only thing that can put an arbitrary byte at column 0 — a raw LF
# inside a string — defeated the column rule and made every bare-metal build that
# pulled such a file fail. Axis 10 is the matching over-correction guard: the
# annotation must still work when it is really at column 0.
#
# `want` here is derived from the DIAGNOSTIC's presence, not from the compiler's
# exit status alone, and the two axes differ only in where the `#host_only` bytes
# sit in the included file.
check_hostonly() {
    ax=$1; want=$2; desc=$3; incbody=$4
    printf '%b' "$incbody" > "$D/hoinc$ax.cyr"
    printf 'include "hoinc%s.cyr"\nsyscall(60, hf());\n' "$ax" > "$D/ho$ax.cyr"
    rc=0
    ( cd "$D" && cat "ho$ax.cyr" | CYRIUS_KERNEL=1 "$CC" > "ho$ax.bin" 2> "ho$ax.err" ) || rc=$?
    got=no
    if grep -q 'bare-metal build includes host-only module' "$D/ho$ax.err"; then got=yes; fi
    if [ "$got" = no ] && [ "$rc" -ne 0 ]; then
        printf '  FAIL: axis %s (%s) failed for an UNRELATED reason: %s\n' \
            "$ax" "$desc" "$(grep -m1 error "$D/ho$ax.err" | cut -c1-90)"
        fail=$((fail+1)); rm -f "$D/ho$ax.bin"; return 0
    fi
    if [ "$got" = no ] && [ ! -s "$D/ho$ax.bin" ]; then
        printf '  FAIL: axis %s (%s) produced an EMPTY binary\n' "$ax" "$desc"
        fail=$((fail+1)); return 0
    fi
    if [ "$got" = "$want" ]; then
        printf '  ok: axis %s — %s (host-only refusal: %s)\n' "$ax" "$desc" "$got"
        pass=$((pass+1))
    else
        printf '  FAIL: axis %s — %s: host-only refusal %s, want %s\n' "$ax" "$desc" "$got" "$want"
        fail=$((fail+1))
    fi
    rm -f "$D/ho$ax.bin"
}

check_hostonly 9 no '#host_only inside a multi-line string is not an annotation' \
'var doc = "intro\n#host_only\nend";\nfn hf(): i64 { return 7; }\n'

check_hostonly 10 yes 'a real column-0 #host_only still refuses a bare-metal build' \
'#host_only\nfn hf(): i64 { return 7; }\n'

if [ "$fail" -gt 0 ]; then
    printf 'FAIL: pp-directive-inside-multiline-string — %s of %s axes failed\n' \
        "$fail" "$((pass+fail))"
    exit 1
fi
printf 'PASS: pp-directive-inside-multiline-string — %s/%s axes green\n' "$pass" "$pass"
