#!/bin/sh
# v6.4.63 — `cyrius build` names version skew between a project-local ./lib/ and
# the version-pinned snapshot (yeo-cy-test filing 2026-07-14).
#
# WHAT THIS GUARDS. A stale ./lib/ shadows the pin. cycc's own note byte-SIZE
# compares ONE sentinel (lib/alloc.cyr) and names nothing, so a consumer could
# not tell "byte-identical" from "three minor versions behind" — yeo-cy-test
# shipped sigil 3.9.8 (pre-dating the 3.9.9 `_SIGIL_CBANK_SLOT` 0->8 crypto fix)
# against a 3.11.1 pin and got only "a shadow exists". The wrapper check names
# the drift, per lib, with the pinned version.
#
# The load-bearing cases, in order of what actually broke:
#   1. BOTH header formats. `cyrius distlib` writes `# Version: X`; sakshi still
#      carries scripts/bundle.sh's `# Bundled distribution of sakshi vX`. A
#      `# Version: `-only parser silently skips sakshi — the BASE LOGGER — which
#      would be the same silent-skip class this issue is about.
#   2. SENTINEL-INDEPENDENCE. The warning must fire when alloc.cyr is
#      byte-IDENTICAL to the snapshot — the case where cycc is totally silent.
#   3. NO FALSE POSITIVE on a fresh lib/ (else it is noise and gets ignored,
#      which is how the original note failed).
#   4. The cyrius source repo must never warn about its own lib/ (it IS the
#      stdlib). Guarded by the NAME-based `[package] name = "cyrius"` signal —
#      NOT `file_exists("src/main.cyr")`, which downstream repos also satisfy
#      (the v6.0.1 conflation bug).
set -e
ROOT=$(cd "$(dirname "$0")/.." && pwd)
CY="$ROOT/build/cyrius"
[ -x "$CY" ] || { echo "SKIP: build/cyrius missing"; exit 0; }
VER=$(cat "$ROOT/VERSION")

W=$(mktemp -d)
trap 'rm -rf "$W"' EXIT

SNAP="$W/home/versions/$VER/lib"
PROJ="$W/proj"
mkdir -p "$SNAP" "$PROJ/lib" "$PROJ/src"

# `syscalls.cyr` is the marker _dep_dir_has_stdlib probes to decide "this lib/
# shadows stdlib at all" — both sides need it.
printf '# syscalls.cyr\n' > "$SNAP/syscalls.cyr"
printf '# alloc.cyr\n'    > "$SNAP/alloc.cyr"
printf '# sigil.cyr -- bundled distribution\n# Version: 3.11.1\n# Generated by: cyrius distlib\n' > "$SNAP/sigil.cyr"
printf '# sakshi.cyr\n# Bundled distribution of sakshi v2.4.6\n' > "$SNAP/sakshi.cyr"

printf '[package]\nname = "lfprobe"\nversion = "0.1.0"\ncyrius = "%s"\n' "$VER" > "$PROJ/cyrius.cyml"
echo 'fn main(): i64 { return 0; }' > "$PROJ/src/main.cyr"

# Case 2: alloc.cyr byte-IDENTICAL — cycc's sentinel sees no drift and says
# nothing. The wrapper check must still fire.
cp "$SNAP/syscalls.cyr" "$SNAP/alloc.cyr" "$PROJ/lib/"
fresh_lib() {
    cp "$SNAP/sigil.cyr" "$SNAP/sakshi.cyr" "$PROJ/lib/"
}
stale_lib() {
    printf '# sigil.cyr -- bundled distribution\n# Version: 3.9.8\n# Generated by: cyrius distlib\n' > "$PROJ/lib/sigil.cyr"
    printf '# sakshi.cyr\n# Bundled distribution of sakshi v2.1.0\n' > "$PROJ/lib/sakshi.cyr"
}
# `if`-guarded so a non-zero build (compile may fail; we only read stderr) does
# not trip `set -e` before the assertion runs.
run_build() {
    ( cd "$PROJ" && CYRIUS_RESOLVED=1 CYRIUS_HOME="$W/home" $EXTRA_ENV \
        "$CY" build $1 src/main.cyr "$W/out.bin" 2>&1 ) > "$W/log" 2>&1 || true
    cat "$W/log"
}

# ---- 1+2: stale, with a byte-identical sentinel -> names BOTH formats --------
stale_lib
cmp -s "$PROJ/lib/alloc.cyr" "$SNAP/alloc.cyr" \
    || { echo "FAIL: fixture broken — alloc.cyr must be byte-identical for the sentinel-independence case"; exit 1; }
EXTRA_ENV=""
out=$(run_build "")
echo "$out" | grep -q "shadows version-pinned" \
    || { echo "FAIL: no skew warning for a stale ./lib/ (alloc.cyr identical — the cycc-silent case)"; echo "$out"; exit 1; }
echo "$out" | grep -q "sigil 3.9.8 (pinned: 3.11.1)" \
    || { echo "FAIL: distlib-format skew not named (expected 'sigil 3.9.8 (pinned: 3.11.1)')"; echo "$out"; exit 1; }
echo "$out" | grep -q "sakshi 2.1.0 (pinned: 2.4.6)" \
    || { echo "FAIL: bundle.sh-format skew not named — a '# Version: '-only parser silently skips sakshi, the base logger"; echo "$out"; exit 1; }

# ---- 3: fresh lib/ -> silent (no false positive) -----------------------------
fresh_lib
out=$(run_build "")
if echo "$out" | grep -q "shadows version-pinned"; then
    echo "FAIL: fresh ./lib/ warned — a check that cries wolf is the bug we are fixing"; echo "$out"; exit 1
fi

# ---- 4: opt-out honored ------------------------------------------------------
stale_lib
EXTRA_ENV="CYRIUS_NO_WARN_SHADOW_LIB=1"
out=$(run_build "")
if echo "$out" | grep -q "shadows version-pinned"; then
    echo "FAIL: CYRIUS_NO_WARN_SHADOW_LIB=1 did not silence the warning"; echo "$out"; exit 1
fi
EXTRA_ENV=""

# ---- 5: --check-lib-sync turns drift into a build failure (CI) ---------------
if ( cd "$PROJ" && CYRIUS_RESOLVED=1 CYRIUS_HOME="$W/home" \
        "$CY" build --check-lib-sync src/main.cyr "$W/out.bin" >/dev/null 2>&1 ); then
    echo "FAIL: --check-lib-sync exited 0 on a stale ./lib/ (must fail the build)"; exit 1
fi

# ---- 6: the cyrius source repo never warns about its own lib/ ----------------
out=$( cd "$ROOT" && "$CY" build "$PROJ/src/main.cyr" "$W/out.bin" 2>&1 || true )
if echo "$out" | grep -q "shadows version-pinned"; then
    echo "FAIL: the cyrius source repo warned about its own lib/ — the name-based"
    echo "      [package] name = \"cyrius\" carve-out regressed to the src/main.cyr conflation"
    echo "$out"; exit 1
fi

echo "PASS: lib freshness — names distlib + bundle.sh skew (sentinel-independent), silent when fresh, opt-out + --check-lib-sync + source-repo carve-out"
