#!/bin/sh
# audit-walk.sh — shared fmt/lint walkers for cyrius audit and scripts/check.sh
#
# Sourced by both `scripts/check.sh` (the cyrius-repo audit) and by the
# `scripts/cyrius` dispatcher's `audit` subcommand, so both paths have
# identical skip-symlink semantics and output shape. If this file is not
# present next to the caller (e.g. old/partial installs), the caller must
# fall back to its own inline implementation.
#
# Functions:
#   audit_fmt_walk CYRFMT DIR [DIR ...]
#       Run cyrfmt on every non-symlink *.cyr file in the given dirs.
#       Sets globals: AW_FMT_FAIL (0/1), AW_FMT_SKIPPED, AW_FMT_FILES
#
#   audit_lint_walk CYRLINT DIR [DIR ...]
#       Run cyrlint on every non-symlink *.cyr file in the given dirs.
#       Sets globals: AW_LINT_TOTAL (warning count), AW_LINT_SKIPPED
#
# Symlinked files are treated as dep files (they belong to upstream and may
# track a different formatter baseline) and are skipped in both walkers.
#
# Files generated by `cyrius distlib` (bundled distributions vendored from
# upstream repos, identified by the "# Generated by: cyrius distlib" marker
# in the file header) are also skipped — they are byte-snapshots of an
# upstream artifact and reformatting them would diverge from the upstream
# build's byte-identity guarantee. Added v5.7.0 for `lib/sandhi.cyr`.

# Returns 0 (true) if the file is a vendored distlib bundle.
# Recognizes three marker styles:
#   1. `# Generated by: cyrius distlib` in the first 5 lines (cyrius
#      distlib output — patra, vani, yukti, sankoch, agnosys, mabda,
#      sandhi, etc.).
#   2. `# Bundled distribution of <name>` in the first 5 lines
#      (scripts/bundle.sh output — sakshi only at v5.8.65 fold; sakshi
#      builds its dist via its own bundle.sh predating cyrius distlib).
#   3. `-- bundled distribution` (the `# <name>.cyr -- bundled
#      distribution` self-declaration used by upstreams running their
#      own regen-dist.sh, e.g. sigil — v6.0.x).
# Any marker means the file is byte-snapshot vendored from upstream and
# re-formatting it would diverge from the upstream byte-identity.
_aw_is_distlib_bundle() {
    head -n 5 "$1" 2>/dev/null | grep -qE "^# Generated by: cyrius distlib$|^# Bundled distribution of |-- bundled distribution"
}

audit_fmt_walk() {
    _cyrfmt="$1"; shift
    AW_FMT_FAIL=0
    AW_FMT_SKIPPED=0
    AW_FMT_FILES=""
    for _dir in "$@"; do
        for _f in "$_dir"/*.cyr; do
            [ -f "$_f" ] || continue
            if [ -L "$_f" ] || _aw_is_distlib_bundle "$_f"; then
                AW_FMT_SKIPPED=$((AW_FMT_SKIPPED + 1))
                continue
            fi
            "$_cyrfmt" "$_f" > /tmp/aw_fmt_$$ 2>/dev/null
            if ! diff -q "$_f" /tmp/aw_fmt_$$ > /dev/null 2>&1; then
                AW_FMT_FAIL=1
                AW_FMT_FILES="$AW_FMT_FILES $(basename "$_f")"
            fi
            rm -f /tmp/aw_fmt_$$
        done
    done
}

audit_lint_walk() {
    _cyrlint="$1"; shift
    AW_LINT_TOTAL=0
    AW_LINT_SKIPPED=0
    for _dir in "$@"; do
        for _f in "$_dir"/*.cyr; do
            [ -f "$_f" ] || continue
            if [ -L "$_f" ] || _aw_is_distlib_bundle "$_f"; then
                AW_LINT_SKIPPED=$((AW_LINT_SKIPPED + 1))
                continue
            fi
            _w=$("$_cyrlint" "$_f" 2>&1 | tail -1 | grep -o '^[0-9]*' || echo 0)
            [ -z "$_w" ] && _w=0
            AW_LINT_TOTAL=$((AW_LINT_TOTAL + _w))
        done
    done
}
